// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.1 (64-bit)
// Version: 2022.2.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rgb2hsv_cv_rgb2hsv_cv,hls_ip_2022_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=3.300000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.692000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=1839,HLS_SYN_LUT=2028,HLS_VERSION=2022_2_1}" *)

module rgb2hsv_cv (
        img_in_TDATA,
        img_in_TKEEP,
        img_in_TSTRB,
        img_in_TUSER,
        img_in_TLAST,
        img_in_TID,
        img_in_TDEST,
        img_out_TDATA,
        img_out_TKEEP,
        img_out_TSTRB,
        img_out_TUSER,
        img_out_TLAST,
        img_out_TID,
        img_out_TDEST,
        rows,
        cols,
        ap_clk,
        ap_rst_n,
        ap_start,
        img_in_TVALID,
        img_in_TREADY,
        img_out_TVALID,
        img_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [31:0] img_in_TDATA;
input  [3:0] img_in_TKEEP;
input  [3:0] img_in_TSTRB;
input  [0:0] img_in_TUSER;
input  [0:0] img_in_TLAST;
input  [0:0] img_in_TID;
input  [0:0] img_in_TDEST;
output  [31:0] img_out_TDATA;
output  [3:0] img_out_TKEEP;
output  [3:0] img_out_TSTRB;
output  [0:0] img_out_TUSER;
output  [0:0] img_out_TLAST;
output  [0:0] img_out_TID;
output  [0:0] img_out_TDEST;
input  [31:0] rows;
input  [31:0] cols;
input   ap_clk;
input   ap_rst_n;
input   ap_start;
input   img_in_TVALID;
output   img_in_TREADY;
output   img_out_TVALID;
input   img_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    Block_entry1_proc_U0_ap_start;
wire    Block_entry1_proc_U0_start_full_n;
wire    Block_entry1_proc_U0_ap_done;
wire    Block_entry1_proc_U0_ap_continue;
wire    Block_entry1_proc_U0_ap_idle;
wire    Block_entry1_proc_U0_ap_ready;
wire    Block_entry1_proc_U0_start_out;
wire    Block_entry1_proc_U0_start_write;
wire   [31:0] Block_entry1_proc_U0_rgb2hsv_out_rows_din;
wire    Block_entry1_proc_U0_rgb2hsv_out_rows_write;
wire   [31:0] Block_entry1_proc_U0_rgb2hsv_out_cols_din;
wire    Block_entry1_proc_U0_rgb2hsv_out_cols_write;
wire   [31:0] Block_entry1_proc_U0_rgb2hsv_in_rows_c9_din;
wire    Block_entry1_proc_U0_rgb2hsv_in_rows_c9_write;
wire   [31:0] Block_entry1_proc_U0_rgb2hsv_in_cols_c10_din;
wire    Block_entry1_proc_U0_rgb2hsv_in_cols_c10_write;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_start;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_done;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_continue;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_idle;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_ready;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_start_out;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_start_write;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_img_in_TREADY;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_img_1_read;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_img_2_read;
wire   [23:0] AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_data18_din;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_data18_write;
wire   [31:0] AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_rows_c_din;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_rows_c_write;
wire   [31:0] AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_cols_c_din;
wire    AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_cols_c_write;
wire    bgr2hsv_patch_9_128_128_1_0_0_U0_ap_start;
wire    bgr2hsv_patch_9_128_128_1_0_0_U0_ap_done;
wire    bgr2hsv_patch_9_128_128_1_0_0_U0_ap_continue;
wire    bgr2hsv_patch_9_128_128_1_0_0_U0_ap_idle;
wire    bgr2hsv_patch_9_128_128_1_0_0_U0_ap_ready;
wire    bgr2hsv_patch_9_128_128_1_0_0_U0_p_src_mat_rows_read;
wire    bgr2hsv_patch_9_128_128_1_0_0_U0_p_src_mat_cols_read;
wire    bgr2hsv_patch_9_128_128_1_0_0_U0_rgb2hsv_in_data18_read;
wire   [23:0] bgr2hsv_patch_9_128_128_1_0_0_U0_rgb2hsv_out_data19_din;
wire    bgr2hsv_patch_9_128_128_1_0_0_U0_rgb2hsv_out_data19_write;
wire    xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_start;
wire    xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_done;
wire    xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_continue;
wire    xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_idle;
wire    xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_ready;
wire    xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_1_read;
wire    xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_2_read;
wire    xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_rgb2hsv_out_data19_read;
wire   [31:0] xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TDATA;
wire    xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TVALID;
wire   [3:0] xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TKEEP;
wire   [3:0] xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TSTRB;
wire   [0:0] xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TUSER;
wire   [0:0] xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TLAST;
wire   [0:0] xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TID;
wire   [0:0] xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TDEST;
wire    rgb2hsv_out_rows_channel_full_n;
wire   [31:0] rgb2hsv_out_rows_channel_dout;
wire   [1:0] rgb2hsv_out_rows_channel_num_data_valid;
wire   [1:0] rgb2hsv_out_rows_channel_fifo_cap;
wire    rgb2hsv_out_rows_channel_empty_n;
wire    rgb2hsv_out_cols_channel_full_n;
wire   [31:0] rgb2hsv_out_cols_channel_dout;
wire   [1:0] rgb2hsv_out_cols_channel_num_data_valid;
wire   [1:0] rgb2hsv_out_cols_channel_fifo_cap;
wire    rgb2hsv_out_cols_channel_empty_n;
wire    rgb2hsv_in_rows_c9_channel_full_n;
wire   [31:0] rgb2hsv_in_rows_c9_channel_dout;
wire   [1:0] rgb2hsv_in_rows_c9_channel_num_data_valid;
wire   [1:0] rgb2hsv_in_rows_c9_channel_fifo_cap;
wire    rgb2hsv_in_rows_c9_channel_empty_n;
wire    rgb2hsv_in_cols_c10_channel_full_n;
wire   [31:0] rgb2hsv_in_cols_c10_channel_dout;
wire   [1:0] rgb2hsv_in_cols_c10_channel_num_data_valid;
wire   [1:0] rgb2hsv_in_cols_c10_channel_fifo_cap;
wire    rgb2hsv_in_cols_c10_channel_empty_n;
wire    rgb2hsv_in_data_full_n;
wire   [23:0] rgb2hsv_in_data_dout;
wire   [1:0] rgb2hsv_in_data_num_data_valid;
wire   [1:0] rgb2hsv_in_data_fifo_cap;
wire    rgb2hsv_in_data_empty_n;
wire    rgb2hsv_in_rows_c_full_n;
wire   [31:0] rgb2hsv_in_rows_c_dout;
wire   [1:0] rgb2hsv_in_rows_c_num_data_valid;
wire   [1:0] rgb2hsv_in_rows_c_fifo_cap;
wire    rgb2hsv_in_rows_c_empty_n;
wire    rgb2hsv_in_cols_c_full_n;
wire   [31:0] rgb2hsv_in_cols_c_dout;
wire   [1:0] rgb2hsv_in_cols_c_num_data_valid;
wire   [1:0] rgb2hsv_in_cols_c_fifo_cap;
wire    rgb2hsv_in_cols_c_empty_n;
wire    rgb2hsv_out_data_full_n;
wire   [23:0] rgb2hsv_out_data_dout;
wire   [1:0] rgb2hsv_out_data_num_data_valid;
wire   [1:0] rgb2hsv_out_data_fifo_cap;
wire    rgb2hsv_out_data_empty_n;
wire   [0:0] start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_din;
wire    start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_full_n;
wire   [0:0] start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_dout;
wire    start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_empty_n;
wire   [0:0] start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_din;
wire    start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_full_n;
wire   [0:0] start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_dout;
wire    start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_empty_n;
wire   [0:0] start_for_bgr2hsv_patch_9_128_128_1_0_0_U0_din;
wire    start_for_bgr2hsv_patch_9_128_128_1_0_0_U0_full_n;
wire   [0:0] start_for_bgr2hsv_patch_9_128_128_1_0_0_U0_dout;
wire    start_for_bgr2hsv_patch_9_128_128_1_0_0_U0_empty_n;

rgb2hsv_cv_Block_entry1_proc Block_entry1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry1_proc_U0_ap_start),
    .start_full_n(Block_entry1_proc_U0_start_full_n),
    .ap_done(Block_entry1_proc_U0_ap_done),
    .ap_continue(Block_entry1_proc_U0_ap_continue),
    .ap_idle(Block_entry1_proc_U0_ap_idle),
    .ap_ready(Block_entry1_proc_U0_ap_ready),
    .start_out(Block_entry1_proc_U0_start_out),
    .start_write(Block_entry1_proc_U0_start_write),
    .rows(rows),
    .cols(cols),
    .rgb2hsv_out_rows_din(Block_entry1_proc_U0_rgb2hsv_out_rows_din),
    .rgb2hsv_out_rows_num_data_valid(rgb2hsv_out_rows_channel_num_data_valid),
    .rgb2hsv_out_rows_fifo_cap(rgb2hsv_out_rows_channel_fifo_cap),
    .rgb2hsv_out_rows_full_n(rgb2hsv_out_rows_channel_full_n),
    .rgb2hsv_out_rows_write(Block_entry1_proc_U0_rgb2hsv_out_rows_write),
    .rgb2hsv_out_cols_din(Block_entry1_proc_U0_rgb2hsv_out_cols_din),
    .rgb2hsv_out_cols_num_data_valid(rgb2hsv_out_cols_channel_num_data_valid),
    .rgb2hsv_out_cols_fifo_cap(rgb2hsv_out_cols_channel_fifo_cap),
    .rgb2hsv_out_cols_full_n(rgb2hsv_out_cols_channel_full_n),
    .rgb2hsv_out_cols_write(Block_entry1_proc_U0_rgb2hsv_out_cols_write),
    .rgb2hsv_in_rows_c9_din(Block_entry1_proc_U0_rgb2hsv_in_rows_c9_din),
    .rgb2hsv_in_rows_c9_num_data_valid(rgb2hsv_in_rows_c9_channel_num_data_valid),
    .rgb2hsv_in_rows_c9_fifo_cap(rgb2hsv_in_rows_c9_channel_fifo_cap),
    .rgb2hsv_in_rows_c9_full_n(rgb2hsv_in_rows_c9_channel_full_n),
    .rgb2hsv_in_rows_c9_write(Block_entry1_proc_U0_rgb2hsv_in_rows_c9_write),
    .rgb2hsv_in_cols_c10_din(Block_entry1_proc_U0_rgb2hsv_in_cols_c10_din),
    .rgb2hsv_in_cols_c10_num_data_valid(rgb2hsv_in_cols_c10_channel_num_data_valid),
    .rgb2hsv_in_cols_c10_fifo_cap(rgb2hsv_in_cols_c10_channel_fifo_cap),
    .rgb2hsv_in_cols_c10_full_n(rgb2hsv_in_cols_c10_channel_full_n),
    .rgb2hsv_in_cols_c10_write(Block_entry1_proc_U0_rgb2hsv_in_cols_c10_write)
);

rgb2hsv_cv_AXIvideo2xfMat_patch_32_9_128_128_1_0_s AXIvideo2xfMat_patch_32_9_128_128_1_0_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_start),
    .start_full_n(start_for_bgr2hsv_patch_9_128_128_1_0_0_U0_full_n),
    .ap_done(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_done),
    .ap_continue(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_continue),
    .ap_idle(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_idle),
    .ap_ready(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_ready),
    .start_out(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_start_out),
    .start_write(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_start_write),
    .img_in_TDATA(img_in_TDATA),
    .img_in_TVALID(img_in_TVALID),
    .img_in_TREADY(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_img_in_TREADY),
    .img_in_TKEEP(img_in_TKEEP),
    .img_in_TSTRB(img_in_TSTRB),
    .img_in_TUSER(img_in_TUSER),
    .img_in_TLAST(img_in_TLAST),
    .img_in_TID(img_in_TID),
    .img_in_TDEST(img_in_TDEST),
    .img_1_dout(rgb2hsv_in_rows_c9_channel_dout),
    .img_1_num_data_valid(rgb2hsv_in_rows_c9_channel_num_data_valid),
    .img_1_fifo_cap(rgb2hsv_in_rows_c9_channel_fifo_cap),
    .img_1_empty_n(rgb2hsv_in_rows_c9_channel_empty_n),
    .img_1_read(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_img_1_read),
    .img_2_dout(rgb2hsv_in_cols_c10_channel_dout),
    .img_2_num_data_valid(rgb2hsv_in_cols_c10_channel_num_data_valid),
    .img_2_fifo_cap(rgb2hsv_in_cols_c10_channel_fifo_cap),
    .img_2_empty_n(rgb2hsv_in_cols_c10_channel_empty_n),
    .img_2_read(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_img_2_read),
    .rgb2hsv_in_data18_din(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_data18_din),
    .rgb2hsv_in_data18_num_data_valid(rgb2hsv_in_data_num_data_valid),
    .rgb2hsv_in_data18_fifo_cap(rgb2hsv_in_data_fifo_cap),
    .rgb2hsv_in_data18_full_n(rgb2hsv_in_data_full_n),
    .rgb2hsv_in_data18_write(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_data18_write),
    .rgb2hsv_in_rows_c_din(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_rows_c_din),
    .rgb2hsv_in_rows_c_num_data_valid(rgb2hsv_in_rows_c_num_data_valid),
    .rgb2hsv_in_rows_c_fifo_cap(rgb2hsv_in_rows_c_fifo_cap),
    .rgb2hsv_in_rows_c_full_n(rgb2hsv_in_rows_c_full_n),
    .rgb2hsv_in_rows_c_write(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_rows_c_write),
    .rgb2hsv_in_cols_c_din(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_cols_c_din),
    .rgb2hsv_in_cols_c_num_data_valid(rgb2hsv_in_cols_c_num_data_valid),
    .rgb2hsv_in_cols_c_fifo_cap(rgb2hsv_in_cols_c_fifo_cap),
    .rgb2hsv_in_cols_c_full_n(rgb2hsv_in_cols_c_full_n),
    .rgb2hsv_in_cols_c_write(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_cols_c_write)
);

rgb2hsv_cv_bgr2hsv_patch_9_128_128_1_0_0_s bgr2hsv_patch_9_128_128_1_0_0_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(bgr2hsv_patch_9_128_128_1_0_0_U0_ap_start),
    .ap_done(bgr2hsv_patch_9_128_128_1_0_0_U0_ap_done),
    .ap_continue(bgr2hsv_patch_9_128_128_1_0_0_U0_ap_continue),
    .ap_idle(bgr2hsv_patch_9_128_128_1_0_0_U0_ap_idle),
    .ap_ready(bgr2hsv_patch_9_128_128_1_0_0_U0_ap_ready),
    .p_src_mat_rows_dout(rgb2hsv_in_rows_c_dout),
    .p_src_mat_rows_num_data_valid(rgb2hsv_in_rows_c_num_data_valid),
    .p_src_mat_rows_fifo_cap(rgb2hsv_in_rows_c_fifo_cap),
    .p_src_mat_rows_empty_n(rgb2hsv_in_rows_c_empty_n),
    .p_src_mat_rows_read(bgr2hsv_patch_9_128_128_1_0_0_U0_p_src_mat_rows_read),
    .p_src_mat_cols_dout(rgb2hsv_in_cols_c_dout),
    .p_src_mat_cols_num_data_valid(rgb2hsv_in_cols_c_num_data_valid),
    .p_src_mat_cols_fifo_cap(rgb2hsv_in_cols_c_fifo_cap),
    .p_src_mat_cols_empty_n(rgb2hsv_in_cols_c_empty_n),
    .p_src_mat_cols_read(bgr2hsv_patch_9_128_128_1_0_0_U0_p_src_mat_cols_read),
    .rgb2hsv_in_data18_dout(rgb2hsv_in_data_dout),
    .rgb2hsv_in_data18_num_data_valid(rgb2hsv_in_data_num_data_valid),
    .rgb2hsv_in_data18_fifo_cap(rgb2hsv_in_data_fifo_cap),
    .rgb2hsv_in_data18_empty_n(rgb2hsv_in_data_empty_n),
    .rgb2hsv_in_data18_read(bgr2hsv_patch_9_128_128_1_0_0_U0_rgb2hsv_in_data18_read),
    .rgb2hsv_out_data19_din(bgr2hsv_patch_9_128_128_1_0_0_U0_rgb2hsv_out_data19_din),
    .rgb2hsv_out_data19_num_data_valid(rgb2hsv_out_data_num_data_valid),
    .rgb2hsv_out_data19_fifo_cap(rgb2hsv_out_data_fifo_cap),
    .rgb2hsv_out_data19_full_n(rgb2hsv_out_data_full_n),
    .rgb2hsv_out_data19_write(bgr2hsv_patch_9_128_128_1_0_0_U0_rgb2hsv_out_data19_write)
);

rgb2hsv_cv_xfMat2AXIvideo_patch_32_9_128_128_1_0_s xfMat2AXIvideo_patch_32_9_128_128_1_0_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_start),
    .ap_done(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_done),
    .ap_continue(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_continue),
    .ap_idle(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_idle),
    .ap_ready(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_ready),
    .img_1_dout(rgb2hsv_out_rows_channel_dout),
    .img_1_num_data_valid(rgb2hsv_out_rows_channel_num_data_valid),
    .img_1_fifo_cap(rgb2hsv_out_rows_channel_fifo_cap),
    .img_1_empty_n(rgb2hsv_out_rows_channel_empty_n),
    .img_1_read(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_1_read),
    .img_2_dout(rgb2hsv_out_cols_channel_dout),
    .img_2_num_data_valid(rgb2hsv_out_cols_channel_num_data_valid),
    .img_2_fifo_cap(rgb2hsv_out_cols_channel_fifo_cap),
    .img_2_empty_n(rgb2hsv_out_cols_channel_empty_n),
    .img_2_read(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_2_read),
    .rgb2hsv_out_data19_dout(rgb2hsv_out_data_dout),
    .rgb2hsv_out_data19_num_data_valid(rgb2hsv_out_data_num_data_valid),
    .rgb2hsv_out_data19_fifo_cap(rgb2hsv_out_data_fifo_cap),
    .rgb2hsv_out_data19_empty_n(rgb2hsv_out_data_empty_n),
    .rgb2hsv_out_data19_read(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_rgb2hsv_out_data19_read),
    .img_out_TDATA(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TDATA),
    .img_out_TVALID(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TVALID),
    .img_out_TREADY(img_out_TREADY),
    .img_out_TKEEP(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TKEEP),
    .img_out_TSTRB(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TSTRB),
    .img_out_TUSER(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TUSER),
    .img_out_TLAST(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TLAST),
    .img_out_TID(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TID),
    .img_out_TDEST(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TDEST)
);

rgb2hsv_cv_fifo_w32_d2_S rgb2hsv_out_rows_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_rgb2hsv_out_rows_din),
    .if_full_n(rgb2hsv_out_rows_channel_full_n),
    .if_write(Block_entry1_proc_U0_rgb2hsv_out_rows_write),
    .if_dout(rgb2hsv_out_rows_channel_dout),
    .if_num_data_valid(rgb2hsv_out_rows_channel_num_data_valid),
    .if_fifo_cap(rgb2hsv_out_rows_channel_fifo_cap),
    .if_empty_n(rgb2hsv_out_rows_channel_empty_n),
    .if_read(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_1_read)
);

rgb2hsv_cv_fifo_w32_d2_S rgb2hsv_out_cols_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_rgb2hsv_out_cols_din),
    .if_full_n(rgb2hsv_out_cols_channel_full_n),
    .if_write(Block_entry1_proc_U0_rgb2hsv_out_cols_write),
    .if_dout(rgb2hsv_out_cols_channel_dout),
    .if_num_data_valid(rgb2hsv_out_cols_channel_num_data_valid),
    .if_fifo_cap(rgb2hsv_out_cols_channel_fifo_cap),
    .if_empty_n(rgb2hsv_out_cols_channel_empty_n),
    .if_read(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_2_read)
);

rgb2hsv_cv_fifo_w32_d2_S rgb2hsv_in_rows_c9_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_rgb2hsv_in_rows_c9_din),
    .if_full_n(rgb2hsv_in_rows_c9_channel_full_n),
    .if_write(Block_entry1_proc_U0_rgb2hsv_in_rows_c9_write),
    .if_dout(rgb2hsv_in_rows_c9_channel_dout),
    .if_num_data_valid(rgb2hsv_in_rows_c9_channel_num_data_valid),
    .if_fifo_cap(rgb2hsv_in_rows_c9_channel_fifo_cap),
    .if_empty_n(rgb2hsv_in_rows_c9_channel_empty_n),
    .if_read(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_img_1_read)
);

rgb2hsv_cv_fifo_w32_d2_S rgb2hsv_in_cols_c10_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_rgb2hsv_in_cols_c10_din),
    .if_full_n(rgb2hsv_in_cols_c10_channel_full_n),
    .if_write(Block_entry1_proc_U0_rgb2hsv_in_cols_c10_write),
    .if_dout(rgb2hsv_in_cols_c10_channel_dout),
    .if_num_data_valid(rgb2hsv_in_cols_c10_channel_num_data_valid),
    .if_fifo_cap(rgb2hsv_in_cols_c10_channel_fifo_cap),
    .if_empty_n(rgb2hsv_in_cols_c10_channel_empty_n),
    .if_read(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_img_2_read)
);

rgb2hsv_cv_fifo_w24_d2_S rgb2hsv_in_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_data18_din),
    .if_full_n(rgb2hsv_in_data_full_n),
    .if_write(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_data18_write),
    .if_dout(rgb2hsv_in_data_dout),
    .if_num_data_valid(rgb2hsv_in_data_num_data_valid),
    .if_fifo_cap(rgb2hsv_in_data_fifo_cap),
    .if_empty_n(rgb2hsv_in_data_empty_n),
    .if_read(bgr2hsv_patch_9_128_128_1_0_0_U0_rgb2hsv_in_data18_read)
);

rgb2hsv_cv_fifo_w32_d2_S rgb2hsv_in_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_rows_c_din),
    .if_full_n(rgb2hsv_in_rows_c_full_n),
    .if_write(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_rows_c_write),
    .if_dout(rgb2hsv_in_rows_c_dout),
    .if_num_data_valid(rgb2hsv_in_rows_c_num_data_valid),
    .if_fifo_cap(rgb2hsv_in_rows_c_fifo_cap),
    .if_empty_n(rgb2hsv_in_rows_c_empty_n),
    .if_read(bgr2hsv_patch_9_128_128_1_0_0_U0_p_src_mat_rows_read)
);

rgb2hsv_cv_fifo_w32_d2_S rgb2hsv_in_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_cols_c_din),
    .if_full_n(rgb2hsv_in_cols_c_full_n),
    .if_write(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_rgb2hsv_in_cols_c_write),
    .if_dout(rgb2hsv_in_cols_c_dout),
    .if_num_data_valid(rgb2hsv_in_cols_c_num_data_valid),
    .if_fifo_cap(rgb2hsv_in_cols_c_fifo_cap),
    .if_empty_n(rgb2hsv_in_cols_c_empty_n),
    .if_read(bgr2hsv_patch_9_128_128_1_0_0_U0_p_src_mat_cols_read)
);

rgb2hsv_cv_fifo_w24_d2_S rgb2hsv_out_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(bgr2hsv_patch_9_128_128_1_0_0_U0_rgb2hsv_out_data19_din),
    .if_full_n(rgb2hsv_out_data_full_n),
    .if_write(bgr2hsv_patch_9_128_128_1_0_0_U0_rgb2hsv_out_data19_write),
    .if_dout(rgb2hsv_out_data_dout),
    .if_num_data_valid(rgb2hsv_out_data_num_data_valid),
    .if_fifo_cap(rgb2hsv_out_data_fifo_cap),
    .if_empty_n(rgb2hsv_out_data_empty_n),
    .if_read(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_rgb2hsv_out_data19_read)
);

rgb2hsv_cv_start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0 start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_din),
    .if_full_n(start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_full_n),
    .if_write(Block_entry1_proc_U0_start_write),
    .if_dout(start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_dout),
    .if_empty_n(start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_empty_n),
    .if_read(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_ready)
);

rgb2hsv_cv_start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0 start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_din),
    .if_full_n(start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_full_n),
    .if_write(Block_entry1_proc_U0_start_write),
    .if_dout(start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_dout),
    .if_empty_n(start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_empty_n),
    .if_read(xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_ready)
);

rgb2hsv_cv_start_for_bgr2hsv_patch_9_128_128_1_0_0_U0 start_for_bgr2hsv_patch_9_128_128_1_0_0_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_bgr2hsv_patch_9_128_128_1_0_0_U0_din),
    .if_full_n(start_for_bgr2hsv_patch_9_128_128_1_0_0_U0_full_n),
    .if_write(AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_start_write),
    .if_dout(start_for_bgr2hsv_patch_9_128_128_1_0_0_U0_dout),
    .if_empty_n(start_for_bgr2hsv_patch_9_128_128_1_0_0_U0_empty_n),
    .if_read(bgr2hsv_patch_9_128_128_1_0_0_U0_ap_ready)
);

assign AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_continue = 1'b1;

assign AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_start = start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_empty_n;

assign Block_entry1_proc_U0_ap_continue = 1'b1;

assign Block_entry1_proc_U0_ap_start = ap_start;

assign Block_entry1_proc_U0_start_full_n = (start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_full_n & start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_full_n);

assign ap_done = xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_done;

assign ap_idle = (xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_idle & bgr2hsv_patch_9_128_128_1_0_0_U0_ap_idle & Block_entry1_proc_U0_ap_idle & AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_ap_idle);

assign ap_ready = Block_entry1_proc_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bgr2hsv_patch_9_128_128_1_0_0_U0_ap_continue = 1'b1;

assign bgr2hsv_patch_9_128_128_1_0_0_U0_ap_start = start_for_bgr2hsv_patch_9_128_128_1_0_0_U0_empty_n;

assign img_in_TREADY = AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_img_in_TREADY;

assign img_out_TDATA = xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TDATA;

assign img_out_TDEST = xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TDEST;

assign img_out_TID = xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TID;

assign img_out_TKEEP = xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TKEEP;

assign img_out_TLAST = xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TLAST;

assign img_out_TSTRB = xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TSTRB;

assign img_out_TUSER = xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TUSER;

assign img_out_TVALID = xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_img_out_TVALID;

assign start_for_AXIvideo2xfMat_patch_32_9_128_128_1_0_U0_din = 1'b1;

assign start_for_bgr2hsv_patch_9_128_128_1_0_0_U0_din = 1'b1;

assign start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_din = 1'b1;

assign xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_continue = 1'b1;

assign xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_ap_start = start_for_xfMat2AXIvideo_patch_32_9_128_128_1_0_U0_empty_n;

endmodule //rgb2hsv_cv
