// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.1 (64-bit)
// Version: 2022.2.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module erode_cv_Block_entry1_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        rows,
        cols,
        erode_out_rows_din,
        erode_out_rows_num_data_valid,
        erode_out_rows_fifo_cap,
        erode_out_rows_full_n,
        erode_out_rows_write,
        erode_out_cols_din,
        erode_out_cols_num_data_valid,
        erode_out_cols_fifo_cap,
        erode_out_cols_full_n,
        erode_out_cols_write,
        erode_in_rows_c9_din,
        erode_in_rows_c9_num_data_valid,
        erode_in_rows_c9_fifo_cap,
        erode_in_rows_c9_full_n,
        erode_in_rows_c9_write,
        erode_in_cols_c10_din,
        erode_in_cols_c10_num_data_valid,
        erode_in_cols_c10_fifo_cap,
        erode_in_cols_c10_full_n,
        erode_in_cols_c10_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] rows;
input  [31:0] cols;
output  [31:0] erode_out_rows_din;
input  [1:0] erode_out_rows_num_data_valid;
input  [1:0] erode_out_rows_fifo_cap;
input   erode_out_rows_full_n;
output   erode_out_rows_write;
output  [31:0] erode_out_cols_din;
input  [1:0] erode_out_cols_num_data_valid;
input  [1:0] erode_out_cols_fifo_cap;
input   erode_out_cols_full_n;
output   erode_out_cols_write;
output  [31:0] erode_in_rows_c9_din;
input  [1:0] erode_in_rows_c9_num_data_valid;
input  [1:0] erode_in_rows_c9_fifo_cap;
input   erode_in_rows_c9_full_n;
output   erode_in_rows_c9_write;
output  [31:0] erode_in_cols_c10_din;
input  [1:0] erode_in_cols_c10_num_data_valid;
input  [1:0] erode_in_cols_c10_fifo_cap;
input   erode_in_cols_c10_full_n;
output   erode_in_cols_c10_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg erode_out_rows_write;
reg erode_out_cols_write;
reg erode_in_rows_c9_write;
reg erode_in_cols_c10_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    erode_out_rows_blk_n;
reg    erode_out_cols_blk_n;
reg    erode_in_rows_c9_blk_n;
reg    erode_in_cols_c10_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (erode_in_cols_c10_full_n == 1'b0) | (erode_in_rows_c9_full_n == 1'b0) | (erode_out_cols_full_n == 1'b0) | (erode_out_rows_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (erode_in_cols_c10_full_n == 1'b0) | (erode_in_rows_c9_full_n == 1'b0) | (erode_out_cols_full_n == 1'b0) | (erode_out_rows_full_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (erode_in_cols_c10_full_n == 1'b0) | (erode_in_rows_c9_full_n == 1'b0) | (erode_out_cols_full_n == 1'b0) | (erode_out_rows_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        erode_in_cols_c10_blk_n = erode_in_cols_c10_full_n;
    end else begin
        erode_in_cols_c10_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (erode_in_cols_c10_full_n == 1'b0) | (erode_in_rows_c9_full_n == 1'b0) | (erode_out_cols_full_n == 1'b0) | (erode_out_rows_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        erode_in_cols_c10_write = 1'b1;
    end else begin
        erode_in_cols_c10_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        erode_in_rows_c9_blk_n = erode_in_rows_c9_full_n;
    end else begin
        erode_in_rows_c9_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (erode_in_cols_c10_full_n == 1'b0) | (erode_in_rows_c9_full_n == 1'b0) | (erode_out_cols_full_n == 1'b0) | (erode_out_rows_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        erode_in_rows_c9_write = 1'b1;
    end else begin
        erode_in_rows_c9_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        erode_out_cols_blk_n = erode_out_cols_full_n;
    end else begin
        erode_out_cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (erode_in_cols_c10_full_n == 1'b0) | (erode_in_rows_c9_full_n == 1'b0) | (erode_out_cols_full_n == 1'b0) | (erode_out_rows_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        erode_out_cols_write = 1'b1;
    end else begin
        erode_out_cols_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        erode_out_rows_blk_n = erode_out_rows_full_n;
    end else begin
        erode_out_rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (erode_in_cols_c10_full_n == 1'b0) | (erode_in_rows_c9_full_n == 1'b0) | (erode_out_cols_full_n == 1'b0) | (erode_out_rows_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        erode_out_rows_write = 1'b1;
    end else begin
        erode_out_rows_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (erode_in_cols_c10_full_n == 1'b0) | (erode_in_rows_c9_full_n == 1'b0) | (erode_out_cols_full_n == 1'b0) | (erode_out_rows_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (erode_in_cols_c10_full_n == 1'b0) | (erode_in_rows_c9_full_n == 1'b0) | (erode_out_cols_full_n == 1'b0) | (erode_out_rows_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign erode_in_cols_c10_din = cols;

assign erode_in_rows_c9_din = rows;

assign erode_out_cols_din = cols;

assign erode_out_rows_din = rows;

assign start_out = real_start;

endmodule //erode_cv_Block_entry1_proc
