// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.1 (64-bit)
// Version: 2022.2.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module erode_cv_xferode_patch_128_128_1_0_1_0_0_0_129_3_3_Pipeline_Col_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        erode_in_data19_dout,
        erode_in_data19_num_data_valid,
        erode_in_data19_fifo_cap,
        erode_in_data19_empty_n,
        erode_in_data19_read,
        erode_out_data20_din,
        erode_out_data20_num_data_valid,
        erode_out_data20_fifo_cap,
        erode_out_data20_full_n,
        erode_out_data20_write,
        img_width,
        buf_V_2_address0,
        buf_V_2_ce0,
        buf_V_2_q0,
        buf_V_2_address1,
        buf_V_2_ce1,
        buf_V_2_we1,
        buf_V_2_d1,
        buf_V_1_address0,
        buf_V_1_ce0,
        buf_V_1_q0,
        buf_V_1_address1,
        buf_V_1_ce1,
        buf_V_1_we1,
        buf_V_1_d1,
        buf_V_address0,
        buf_V_ce0,
        buf_V_q0,
        buf_V_address1,
        buf_V_ce1,
        buf_V_we1,
        buf_V_d1,
        p_cast1,
        p_cast2,
        p_cast,
        cmp_i_i142_i
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] erode_in_data19_dout;
input  [1:0] erode_in_data19_num_data_valid;
input  [1:0] erode_in_data19_fifo_cap;
input   erode_in_data19_empty_n;
output   erode_in_data19_read;
output  [7:0] erode_out_data20_din;
input  [1:0] erode_out_data20_num_data_valid;
input  [1:0] erode_out_data20_fifo_cap;
input   erode_out_data20_full_n;
output   erode_out_data20_write;
input  [15:0] img_width;
output  [6:0] buf_V_2_address0;
output   buf_V_2_ce0;
input  [7:0] buf_V_2_q0;
output  [6:0] buf_V_2_address1;
output   buf_V_2_ce1;
output   buf_V_2_we1;
output  [7:0] buf_V_2_d1;
output  [6:0] buf_V_1_address0;
output   buf_V_1_ce0;
input  [7:0] buf_V_1_q0;
output  [6:0] buf_V_1_address1;
output   buf_V_1_ce1;
output   buf_V_1_we1;
output  [7:0] buf_V_1_d1;
output  [6:0] buf_V_address0;
output   buf_V_ce0;
input  [7:0] buf_V_q0;
output  [6:0] buf_V_address1;
output   buf_V_ce1;
output   buf_V_we1;
output  [7:0] buf_V_d1;
input  [1:0] p_cast1;
input  [1:0] p_cast2;
input  [1:0] p_cast;
input  [0:0] cmp_i_i142_i;

reg ap_idle;
reg erode_in_data19_read;
reg erode_out_data20_write;
reg buf_V_2_ce0;
reg[6:0] buf_V_2_address1;
reg buf_V_2_ce1;
reg buf_V_2_we1;
reg[7:0] buf_V_2_d1;
reg buf_V_1_ce0;
reg[6:0] buf_V_1_address1;
reg buf_V_1_ce1;
reg buf_V_1_we1;
reg[7:0] buf_V_1_d1;
reg buf_V_ce0;
reg[6:0] buf_V_address1;
reg buf_V_ce1;
reg buf_V_we1;
reg[7:0] buf_V_d1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln1027_reg_633;
reg   [0:0] icmp_ln1027_1_reg_637;
wire   [0:0] cmp_i_i142_i_read_reg_608;
reg    ap_predicate_op50_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
reg   [0:0] icmp_ln1031_reg_655;
reg   [0:0] icmp_ln1031_reg_655_pp0_iter9_reg;
reg    ap_block_state11_pp0_stage0_iter10;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1027_fu_348_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    erode_in_data19_blk_n;
wire    ap_block_pp0_stage0;
reg    erode_out_data20_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] p_cast_read_reg_612;
reg   [12:0] col_V_1_reg_627;
reg   [12:0] col_V_1_reg_627_pp0_iter1_reg;
reg   [0:0] icmp_ln1027_reg_633_pp0_iter1_reg;
reg   [0:0] icmp_ln1027_reg_633_pp0_iter2_reg;
reg   [0:0] icmp_ln1027_reg_633_pp0_iter3_reg;
reg   [0:0] icmp_ln1027_reg_633_pp0_iter4_reg;
reg   [0:0] icmp_ln1027_reg_633_pp0_iter5_reg;
reg   [0:0] icmp_ln1027_reg_633_pp0_iter6_reg;
reg   [0:0] icmp_ln1027_reg_633_pp0_iter7_reg;
wire   [0:0] icmp_ln1027_1_fu_360_p2;
reg   [0:0] icmp_ln1027_1_reg_637_pp0_iter1_reg;
reg   [0:0] icmp_ln1027_1_reg_637_pp0_iter2_reg;
reg   [0:0] icmp_ln1027_1_reg_637_pp0_iter3_reg;
reg   [7:0] erode_in_data19_read_reg_641;
wire   [63:0] conv_i99_i_fu_371_p1;
reg   [63:0] conv_i99_i_reg_648;
wire   [0:0] icmp_ln1031_fu_380_p2;
reg   [0:0] icmp_ln1031_reg_655_pp0_iter3_reg;
reg   [0:0] icmp_ln1031_reg_655_pp0_iter4_reg;
reg   [0:0] icmp_ln1031_reg_655_pp0_iter5_reg;
reg   [0:0] icmp_ln1031_reg_655_pp0_iter6_reg;
reg   [0:0] icmp_ln1031_reg_655_pp0_iter7_reg;
reg   [0:0] icmp_ln1031_reg_655_pp0_iter8_reg;
wire   [7:0] buf_cop_V_fu_385_p5;
wire   [7:0] buf_cop_V_1_fu_396_p5;
wire   [7:0] buf_cop_V_2_fu_407_p5;
wire   [7:0] src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_288_ap_return;
reg   [7:0] src_buf_temp_copy_extract_V_0_reg_689;
wire   [7:0] src_buf_temp_copy_extract_V_0_4_xfExtractPixels_1_1_0_s_fu_294_ap_return;
reg   [7:0] src_buf_temp_copy_extract_V_0_4_reg_694;
reg   [7:0] src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter6_reg;
reg   [7:0] src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter7_reg;
reg   [7:0] src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter8_reg;
reg   [7:0] src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter9_reg;
wire   [7:0] max_V_11_fu_430_p3;
reg   [7:0] max_V_11_reg_701;
wire   [0:0] icmp_ln1027_3_fu_438_p2;
reg   [0:0] icmp_ln1027_3_reg_706;
reg   [7:0] src_buf_temp_med_apply_V_6_reg_711;
wire   [7:0] src_buf_temp_copy_extract_V_0_3_xfExtractPixels_1_1_0_s_fu_300_ap_return;
reg   [7:0] src_buf_temp_copy_extract_V_0_3_reg_717;
reg   [7:0] src_buf_temp_copy_extract_V_0_3_reg_717_pp0_iter7_reg;
wire   [7:0] max_V_14_fu_471_p3;
reg   [7:0] max_V_14_reg_723;
wire   [7:0] max_V_15_fu_493_p3;
reg   [7:0] max_V_15_reg_729;
wire   [0:0] icmp_ln1027_6_fu_499_p2;
reg   [0:0] icmp_ln1027_6_reg_734;
reg   [7:0] src_buf_temp_med_apply_V_7_reg_739;
wire   [7:0] max_V_18_fu_521_p3;
reg   [7:0] max_V_18_reg_745;
wire   [7:0] max_V_20_fu_542_p3;
reg   [7:0] max_V_20_reg_751;
wire   [0:0] icmp_ln1027_9_fu_548_p2;
reg   [0:0] icmp_ln1027_9_reg_756;
reg    ap_condition_exit_pp0_iter8_stage0;
wire    src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_288_ap_ready;
wire    src_buf_temp_copy_extract_V_0_4_xfExtractPixels_1_1_0_s_fu_294_ap_ready;
wire    src_buf_temp_copy_extract_V_0_3_xfExtractPixels_1_1_0_s_fu_300_ap_ready;
wire   [7:0] ap_phi_reg_pp0_iter0_buf_cop_V_0_reg_255;
reg   [7:0] ap_phi_reg_pp0_iter1_buf_cop_V_0_reg_255;
reg   [7:0] ap_phi_reg_pp0_iter2_buf_cop_V_0_reg_255;
reg   [7:0] ap_phi_reg_pp0_iter3_buf_cop_V_0_reg_255;
reg   [7:0] ap_phi_reg_pp0_iter4_buf_cop_V_0_reg_255;
reg   [7:0] ap_phi_reg_pp0_iter5_buf_cop_V_0_reg_255;
wire   [7:0] ap_phi_reg_pp0_iter0_buf_cop_V_3_reg_266;
reg   [7:0] ap_phi_reg_pp0_iter1_buf_cop_V_3_reg_266;
reg   [7:0] ap_phi_reg_pp0_iter2_buf_cop_V_3_reg_266;
reg   [7:0] ap_phi_reg_pp0_iter3_buf_cop_V_3_reg_266;
reg   [7:0] ap_phi_reg_pp0_iter4_buf_cop_V_3_reg_266;
reg   [7:0] ap_phi_reg_pp0_iter5_buf_cop_V_3_reg_266;
wire   [7:0] ap_phi_reg_pp0_iter0_buf_cop_V_1_0_reg_277;
reg   [7:0] ap_phi_reg_pp0_iter1_buf_cop_V_1_0_reg_277;
reg   [7:0] ap_phi_reg_pp0_iter2_buf_cop_V_1_0_reg_277;
reg   [7:0] ap_phi_reg_pp0_iter3_buf_cop_V_1_0_reg_277;
reg   [7:0] ap_phi_reg_pp0_iter4_buf_cop_V_1_0_reg_277;
reg   [7:0] ap_phi_reg_pp0_iter5_buf_cop_V_1_0_reg_277;
reg   [7:0] ap_phi_reg_pp0_iter6_buf_cop_V_1_0_reg_277;
wire   [6:0] buf_V_addr_gep_fu_207_p3;
wire   [6:0] buf_V_1_addr_gep_fu_214_p3;
wire   [6:0] buf_V_2_addr_gep_fu_221_p3;
reg   [12:0] col_V_fu_82;
wire   [12:0] col_V_2_fu_354_p2;
wire    ap_loop_init;
reg   [12:0] ap_sig_allocacmp_col_V_1;
reg   [7:0] max_V_fu_86;
reg   [7:0] max_V_1_fu_90;
reg   [7:0] ret_fu_94;
reg   [7:0] max_V_2_fu_98;
reg   [7:0] ret_1_fu_102;
reg   [7:0] max_V_5_fu_106;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] zext_ln1027_fu_344_p1;
wire   [0:0] icmp_ln1027_2_fu_424_p2;
wire   [7:0] max_V_13_fu_460_p3;
wire   [0:0] icmp_ln1027_4_fu_465_p2;
wire   [0:0] icmp_ln1027_5_fu_489_p2;
wire   [7:0] max_V_17_fu_510_p3;
wire   [0:0] icmp_ln1027_7_fu_515_p2;
wire   [0:0] icmp_ln1027_8_fu_538_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_359;
reg    ap_condition_655;
reg    ap_condition_659;
reg    ap_condition_662;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_done_reg = 1'b0;
end

erode_cv_xfExtractPixels_1_1_0_s src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_288(
    .ap_ready(src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_288_ap_ready),
    .p_read1(ap_phi_reg_pp0_iter5_buf_cop_V_0_reg_255),
    .ap_return(src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_288_ap_return)
);

erode_cv_xfExtractPixels_1_1_0_s src_buf_temp_copy_extract_V_0_4_xfExtractPixels_1_1_0_s_fu_294(
    .ap_ready(src_buf_temp_copy_extract_V_0_4_xfExtractPixels_1_1_0_s_fu_294_ap_ready),
    .p_read1(ap_phi_reg_pp0_iter5_buf_cop_V_3_reg_266),
    .ap_return(src_buf_temp_copy_extract_V_0_4_xfExtractPixels_1_1_0_s_fu_294_ap_return)
);

erode_cv_xfExtractPixels_1_1_0_s src_buf_temp_copy_extract_V_0_3_xfExtractPixels_1_1_0_s_fu_300(
    .ap_ready(src_buf_temp_copy_extract_V_0_3_xfExtractPixels_1_1_0_s_fu_300_ap_ready),
    .p_read1(ap_phi_reg_pp0_iter6_buf_cop_V_1_0_reg_277),
    .ap_return(src_buf_temp_copy_extract_V_0_3_xfExtractPixels_1_1_0_s_fu_300_ap_return)
);

erode_cv_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U42(
    .din0(buf_V_q0),
    .din1(buf_V_1_q0),
    .din2(buf_V_2_q0),
    .din3(p_cast1),
    .dout(buf_cop_V_fu_385_p5)
);

erode_cv_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U43(
    .din0(buf_V_q0),
    .din1(buf_V_1_q0),
    .din2(buf_V_2_q0),
    .din3(p_cast2),
    .dout(buf_cop_V_1_fu_396_p5)
);

erode_cv_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U44(
    .din0(buf_V_q0),
    .din1(buf_V_1_q0),
    .din2(buf_V_2_q0),
    .din3(p_cast),
    .dout(buf_cop_V_2_fu_407_p5)
);

erode_cv_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter8_stage0)) begin
            ap_enable_reg_pp0_iter9 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_359)) begin
        if (((icmp_ln1027_1_fu_360_p2 == 1'd0) & (icmp_ln1027_fu_348_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_buf_cop_V_0_reg_255 <= 8'd255;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_buf_cop_V_0_reg_255 <= ap_phi_reg_pp0_iter0_buf_cop_V_0_reg_255;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_359)) begin
        if (((icmp_ln1027_1_fu_360_p2 == 1'd0) & (icmp_ln1027_fu_348_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_buf_cop_V_1_0_reg_277 <= 8'd255;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_buf_cop_V_1_0_reg_277 <= ap_phi_reg_pp0_iter0_buf_cop_V_1_0_reg_277;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_359)) begin
        if (((icmp_ln1027_1_fu_360_p2 == 1'd0) & (icmp_ln1027_fu_348_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_buf_cop_V_3_reg_266 <= 8'd255;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_buf_cop_V_3_reg_266 <= ap_phi_reg_pp0_iter0_buf_cop_V_3_reg_266;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln1027_1_reg_637_pp0_iter3_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_buf_cop_V_0_reg_255 <= buf_cop_V_fu_385_p5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_buf_cop_V_0_reg_255 <= ap_phi_reg_pp0_iter4_buf_cop_V_0_reg_255;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln1027_1_reg_637_pp0_iter3_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_buf_cop_V_1_0_reg_277 <= buf_cop_V_1_fu_396_p5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_buf_cop_V_1_0_reg_277 <= ap_phi_reg_pp0_iter4_buf_cop_V_1_0_reg_277;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln1027_1_reg_637_pp0_iter3_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_buf_cop_V_3_reg_266 <= buf_cop_V_2_fu_407_p5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_buf_cop_V_3_reg_266 <= ap_phi_reg_pp0_iter4_buf_cop_V_3_reg_266;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln1027_fu_348_p2 == 1'd0))) begin
            col_V_fu_82 <= col_V_2_fu_354_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_V_fu_82 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            max_V_1_fu_90 <= 8'd255;
        end else if (((ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1027_reg_633_pp0_iter5_reg == 1'd0))) begin
            max_V_1_fu_90 <= ret_1_fu_102;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            max_V_2_fu_98 <= 8'd255;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1027_reg_633_pp0_iter4_reg == 1'd0))) begin
            max_V_2_fu_98 <= src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_288_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            max_V_5_fu_106 <= 8'd255;
        end else if (((ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln1027_reg_633_pp0_iter7_reg == 1'd0))) begin
            max_V_5_fu_106 <= src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter7_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            max_V_fu_86 <= 8'd255;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1027_reg_633_pp0_iter4_reg == 1'd0))) begin
            max_V_fu_86 <= max_V_2_fu_98;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ret_1_fu_102 <= 8'd255;
        end else if (((ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1027_reg_633_pp0_iter5_reg == 1'd0))) begin
            ret_1_fu_102 <= src_buf_temp_copy_extract_V_0_3_xfExtractPixels_1_1_0_s_fu_300_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ret_fu_94 <= 8'd255;
        end else if (((ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln1027_reg_633_pp0_iter7_reg == 1'd0))) begin
            ret_fu_94 <= max_V_5_fu_106;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        col_V_1_reg_627 <= ap_sig_allocacmp_col_V_1;
        col_V_1_reg_627_pp0_iter1_reg <= col_V_1_reg_627;
        icmp_ln1027_1_reg_637_pp0_iter1_reg <= icmp_ln1027_1_reg_637;
        icmp_ln1027_reg_633 <= icmp_ln1027_fu_348_p2;
        icmp_ln1027_reg_633_pp0_iter1_reg <= icmp_ln1027_reg_633;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln1027_1_reg_637_pp0_iter2_reg <= icmp_ln1027_1_reg_637_pp0_iter1_reg;
        icmp_ln1027_1_reg_637_pp0_iter3_reg <= icmp_ln1027_1_reg_637_pp0_iter2_reg;
        icmp_ln1027_9_reg_756 <= icmp_ln1027_9_fu_548_p2;
        icmp_ln1027_reg_633_pp0_iter2_reg <= icmp_ln1027_reg_633_pp0_iter1_reg;
        icmp_ln1027_reg_633_pp0_iter3_reg <= icmp_ln1027_reg_633_pp0_iter2_reg;
        icmp_ln1027_reg_633_pp0_iter4_reg <= icmp_ln1027_reg_633_pp0_iter3_reg;
        icmp_ln1027_reg_633_pp0_iter5_reg <= icmp_ln1027_reg_633_pp0_iter4_reg;
        icmp_ln1027_reg_633_pp0_iter6_reg <= icmp_ln1027_reg_633_pp0_iter5_reg;
        icmp_ln1027_reg_633_pp0_iter7_reg <= icmp_ln1027_reg_633_pp0_iter6_reg;
        icmp_ln1031_reg_655_pp0_iter3_reg <= icmp_ln1031_reg_655;
        icmp_ln1031_reg_655_pp0_iter4_reg <= icmp_ln1031_reg_655_pp0_iter3_reg;
        icmp_ln1031_reg_655_pp0_iter5_reg <= icmp_ln1031_reg_655_pp0_iter4_reg;
        icmp_ln1031_reg_655_pp0_iter6_reg <= icmp_ln1031_reg_655_pp0_iter5_reg;
        icmp_ln1031_reg_655_pp0_iter7_reg <= icmp_ln1031_reg_655_pp0_iter6_reg;
        icmp_ln1031_reg_655_pp0_iter8_reg <= icmp_ln1031_reg_655_pp0_iter7_reg;
        icmp_ln1031_reg_655_pp0_iter9_reg <= icmp_ln1031_reg_655_pp0_iter8_reg;
        max_V_20_reg_751 <= max_V_20_fu_542_p3;
        src_buf_temp_copy_extract_V_0_3_reg_717_pp0_iter7_reg <= src_buf_temp_copy_extract_V_0_3_reg_717;
        src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter6_reg <= src_buf_temp_copy_extract_V_0_4_reg_694;
        src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter7_reg <= src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter6_reg;
        src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter8_reg <= src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter7_reg;
        src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter9_reg <= src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter8_reg;
        src_buf_temp_med_apply_V_6_reg_711 <= ret_1_fu_102;
        src_buf_temp_med_apply_V_7_reg_739 <= max_V_5_fu_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_buf_cop_V_0_reg_255 <= ap_phi_reg_pp0_iter1_buf_cop_V_0_reg_255;
        ap_phi_reg_pp0_iter2_buf_cop_V_1_0_reg_277 <= ap_phi_reg_pp0_iter1_buf_cop_V_1_0_reg_277;
        ap_phi_reg_pp0_iter2_buf_cop_V_3_reg_266 <= ap_phi_reg_pp0_iter1_buf_cop_V_3_reg_266;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_buf_cop_V_0_reg_255 <= ap_phi_reg_pp0_iter2_buf_cop_V_0_reg_255;
        ap_phi_reg_pp0_iter3_buf_cop_V_1_0_reg_277 <= ap_phi_reg_pp0_iter2_buf_cop_V_1_0_reg_277;
        ap_phi_reg_pp0_iter3_buf_cop_V_3_reg_266 <= ap_phi_reg_pp0_iter2_buf_cop_V_3_reg_266;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_buf_cop_V_0_reg_255 <= ap_phi_reg_pp0_iter3_buf_cop_V_0_reg_255;
        ap_phi_reg_pp0_iter4_buf_cop_V_1_0_reg_277 <= ap_phi_reg_pp0_iter3_buf_cop_V_1_0_reg_277;
        ap_phi_reg_pp0_iter4_buf_cop_V_3_reg_266 <= ap_phi_reg_pp0_iter3_buf_cop_V_3_reg_266;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_buf_cop_V_1_0_reg_277 <= ap_phi_reg_pp0_iter5_buf_cop_V_1_0_reg_277;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        conv_i99_i_reg_648[12 : 0] <= conv_i99_i_fu_371_p1[12 : 0];
        icmp_ln1031_reg_655 <= icmp_ln1031_fu_380_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op50_read_state2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        erode_in_data19_read_reg_641 <= erode_in_data19_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1027_fu_348_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln1027_1_reg_637 <= icmp_ln1027_1_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_reg_633_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln1027_3_reg_706 <= icmp_ln1027_3_fu_438_p2;
        max_V_11_reg_701 <= max_V_11_fu_430_p3;
        src_buf_temp_copy_extract_V_0_4_reg_694 <= src_buf_temp_copy_extract_V_0_4_xfExtractPixels_1_1_0_s_fu_294_ap_return;
        src_buf_temp_copy_extract_V_0_reg_689 <= src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_288_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_reg_633_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln1027_6_reg_734 <= icmp_ln1027_6_fu_499_p2;
        max_V_15_reg_729 <= max_V_15_fu_493_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_reg_633_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        max_V_14_reg_723 <= max_V_14_fu_471_p3;
        src_buf_temp_copy_extract_V_0_3_reg_717 <= src_buf_temp_copy_extract_V_0_3_xfExtractPixels_1_1_0_s_fu_300_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_reg_633_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        max_V_18_reg_745 <= max_V_18_fu_521_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1027_fu_348_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln1027_reg_633_pp0_iter7_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter8_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter8_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_col_V_1 = 13'd0;
    end else begin
        ap_sig_allocacmp_col_V_1 = col_V_fu_82;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_655)) begin
        if ((cmp_i_i142_i == 1'd1)) begin
            buf_V_1_address1 = buf_V_1_addr_gep_fu_214_p3;
        end else if ((cmp_i_i142_i_read_reg_608 == 1'd0)) begin
            buf_V_1_address1 = conv_i99_i_fu_371_p1;
        end else begin
            buf_V_1_address1 = 'bx;
        end
    end else begin
        buf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buf_V_1_ce0 = 1'b1;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i142_i == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (p_cast_read_reg_612 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp_i_i142_i_read_reg_608 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (p_cast_read_reg_612 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_1_ce1 = 1'b1;
    end else begin
        buf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_655)) begin
        if ((cmp_i_i142_i == 1'd1)) begin
            buf_V_1_d1 = erode_in_data19_read_reg_641;
        end else if ((cmp_i_i142_i_read_reg_608 == 1'd0)) begin
            buf_V_1_d1 = 8'd255;
        end else begin
            buf_V_1_d1 = 'bx;
        end
    end else begin
        buf_V_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp_i_i142_i == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (p_cast_read_reg_612 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp_i_i142_i_read_reg_608 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (p_cast_read_reg_612 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_1_we1 = 1'b1;
    end else begin
        buf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_659)) begin
        if ((cmp_i_i142_i == 1'd1)) begin
            buf_V_2_address1 = buf_V_2_addr_gep_fu_221_p3;
        end else if ((cmp_i_i142_i_read_reg_608 == 1'd0)) begin
            buf_V_2_address1 = conv_i99_i_fu_371_p1;
        end else begin
            buf_V_2_address1 = 'bx;
        end
    end else begin
        buf_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buf_V_2_ce0 = 1'b1;
    end else begin
        buf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(p_cast_read_reg_612 == 2'd0) & ~(p_cast_read_reg_612 == 2'd1) & (cmp_i_i142_i == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~(p_cast_read_reg_612 == 2'd0) & ~(p_cast_read_reg_612 == 2'd1) & (cmp_i_i142_i_read_reg_608 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_2_ce1 = 1'b1;
    end else begin
        buf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_659)) begin
        if ((cmp_i_i142_i == 1'd1)) begin
            buf_V_2_d1 = erode_in_data19_read_reg_641;
        end else if ((cmp_i_i142_i_read_reg_608 == 1'd0)) begin
            buf_V_2_d1 = 8'd255;
        end else begin
            buf_V_2_d1 = 'bx;
        end
    end else begin
        buf_V_2_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(p_cast_read_reg_612 == 2'd0) & ~(p_cast_read_reg_612 == 2'd1) & (cmp_i_i142_i == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~(p_cast_read_reg_612 == 2'd0) & ~(p_cast_read_reg_612 == 2'd1) & (cmp_i_i142_i_read_reg_608 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_2_we1 = 1'b1;
    end else begin
        buf_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_662)) begin
        if ((cmp_i_i142_i == 1'd1)) begin
            buf_V_address1 = buf_V_addr_gep_fu_207_p3;
        end else if ((cmp_i_i142_i_read_reg_608 == 1'd0)) begin
            buf_V_address1 = conv_i99_i_fu_371_p1;
        end else begin
            buf_V_address1 = 'bx;
        end
    end else begin
        buf_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buf_V_ce0 = 1'b1;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i142_i == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (p_cast_read_reg_612 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp_i_i142_i_read_reg_608 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (p_cast_read_reg_612 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_ce1 = 1'b1;
    end else begin
        buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_662)) begin
        if ((cmp_i_i142_i == 1'd1)) begin
            buf_V_d1 = erode_in_data19_read_reg_641;
        end else if ((cmp_i_i142_i_read_reg_608 == 1'd0)) begin
            buf_V_d1 = 8'd255;
        end else begin
            buf_V_d1 = 'bx;
        end
    end else begin
        buf_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp_i_i142_i == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (p_cast_read_reg_612 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cmp_i_i142_i_read_reg_608 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (p_cast_read_reg_612 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_V_we1 = 1'b1;
    end else begin
        buf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op50_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        erode_in_data19_blk_n = erode_in_data19_empty_n;
    end else begin
        erode_in_data19_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op50_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        erode_in_data19_read = 1'b1;
    end else begin
        erode_in_data19_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1031_reg_655_pp0_iter9_reg == 1'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        erode_out_data20_blk_n = erode_out_data20_full_n;
    end else begin
        erode_out_data20_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln1031_reg_655_pp0_iter9_reg == 1'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        erode_out_data20_write = 1'b1;
    end else begin
        erode_out_data20_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln1031_reg_655_pp0_iter9_reg == 1'd0) & (erode_out_data20_full_n == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((ap_predicate_op50_read_state2 == 1'b1) & (erode_in_data19_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln1031_reg_655_pp0_iter9_reg == 1'd0) & (erode_out_data20_full_n == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((ap_predicate_op50_read_state2 == 1'b1) & (erode_in_data19_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln1031_reg_655_pp0_iter9_reg == 1'd0) & (erode_out_data20_full_n == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((ap_predicate_op50_read_state2 == 1'b1) & (erode_in_data19_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp0_stage0_iter10 = ((icmp_ln1031_reg_655_pp0_iter9_reg == 1'd0) & (erode_out_data20_full_n == 1'b0));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op50_read_state2 == 1'b1) & (erode_in_data19_empty_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_359 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_655 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (p_cast_read_reg_612 == 2'd1) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_659 = (~(p_cast_read_reg_612 == 2'd0) & ~(p_cast_read_reg_612 == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_662 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_1_reg_637_pp0_iter1_reg == 1'd1) & (icmp_ln1027_reg_633_pp0_iter1_reg == 1'd0) & (p_cast_read_reg_612 == 2'd0) & (1'b0 == ap_block_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_buf_cop_V_0_reg_255 = 'bx;

assign ap_phi_reg_pp0_iter0_buf_cop_V_1_0_reg_277 = 'bx;

assign ap_phi_reg_pp0_iter0_buf_cop_V_3_reg_266 = 'bx;

always @ (*) begin
    ap_predicate_op50_read_state2 = ((cmp_i_i142_i == 1'd1) & (icmp_ln1027_1_reg_637 == 1'd1) & (icmp_ln1027_reg_633 == 1'd0));
end

assign buf_V_1_addr_gep_fu_214_p3 = conv_i99_i_fu_371_p1;

assign buf_V_1_address0 = conv_i99_i_reg_648;

assign buf_V_2_addr_gep_fu_221_p3 = conv_i99_i_fu_371_p1;

assign buf_V_2_address0 = conv_i99_i_reg_648;

assign buf_V_addr_gep_fu_207_p3 = conv_i99_i_fu_371_p1;

assign buf_V_address0 = conv_i99_i_reg_648;

assign cmp_i_i142_i_read_reg_608 = cmp_i_i142_i;

assign col_V_2_fu_354_p2 = (ap_sig_allocacmp_col_V_1 + 13'd1);

assign conv_i99_i_fu_371_p1 = col_V_1_reg_627_pp0_iter1_reg;

assign erode_out_data20_din = ((icmp_ln1027_9_reg_756[0:0] == 1'b1) ? src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter9_reg : max_V_20_reg_751);

assign icmp_ln1027_1_fu_360_p2 = ((zext_ln1027_fu_344_p1 < img_width) ? 1'b1 : 1'b0);

assign icmp_ln1027_2_fu_424_p2 = ((max_V_fu_86 > max_V_2_fu_98) ? 1'b1 : 1'b0);

assign icmp_ln1027_3_fu_438_p2 = ((max_V_11_fu_430_p3 > src_buf_temp_copy_extract_V_0_xfExtractPixels_1_1_0_s_fu_288_ap_return) ? 1'b1 : 1'b0);

assign icmp_ln1027_4_fu_465_p2 = ((max_V_13_fu_460_p3 > max_V_1_fu_90) ? 1'b1 : 1'b0);

assign icmp_ln1027_5_fu_489_p2 = ((max_V_14_reg_723 > src_buf_temp_med_apply_V_6_reg_711) ? 1'b1 : 1'b0);

assign icmp_ln1027_6_fu_499_p2 = ((max_V_15_fu_493_p3 > src_buf_temp_copy_extract_V_0_3_reg_717) ? 1'b1 : 1'b0);

assign icmp_ln1027_7_fu_515_p2 = ((max_V_17_fu_510_p3 > ret_fu_94) ? 1'b1 : 1'b0);

assign icmp_ln1027_8_fu_538_p2 = ((max_V_18_reg_745 > src_buf_temp_med_apply_V_7_reg_739) ? 1'b1 : 1'b0);

assign icmp_ln1027_9_fu_548_p2 = ((max_V_20_fu_542_p3 > src_buf_temp_copy_extract_V_0_4_reg_694_pp0_iter8_reg) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_348_p2 = ((zext_ln1027_fu_344_p1 > img_width) ? 1'b1 : 1'b0);

assign icmp_ln1031_fu_380_p2 = ((col_V_1_reg_627_pp0_iter1_reg == 13'd0) ? 1'b1 : 1'b0);

assign max_V_11_fu_430_p3 = ((icmp_ln1027_2_fu_424_p2[0:0] == 1'b1) ? max_V_2_fu_98 : max_V_fu_86);

assign max_V_13_fu_460_p3 = ((icmp_ln1027_3_reg_706[0:0] == 1'b1) ? src_buf_temp_copy_extract_V_0_reg_689 : max_V_11_reg_701);

assign max_V_14_fu_471_p3 = ((icmp_ln1027_4_fu_465_p2[0:0] == 1'b1) ? max_V_1_fu_90 : max_V_13_fu_460_p3);

assign max_V_15_fu_493_p3 = ((icmp_ln1027_5_fu_489_p2[0:0] == 1'b1) ? src_buf_temp_med_apply_V_6_reg_711 : max_V_14_reg_723);

assign max_V_17_fu_510_p3 = ((icmp_ln1027_6_reg_734[0:0] == 1'b1) ? src_buf_temp_copy_extract_V_0_3_reg_717_pp0_iter7_reg : max_V_15_reg_729);

assign max_V_18_fu_521_p3 = ((icmp_ln1027_7_fu_515_p2[0:0] == 1'b1) ? ret_fu_94 : max_V_17_fu_510_p3);

assign max_V_20_fu_542_p3 = ((icmp_ln1027_8_fu_538_p2[0:0] == 1'b1) ? src_buf_temp_med_apply_V_7_reg_739 : max_V_18_reg_745);

assign p_cast_read_reg_612 = p_cast;

assign zext_ln1027_fu_344_p1 = ap_sig_allocacmp_col_V_1;

always @ (posedge ap_clk) begin
    conv_i99_i_reg_648[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
end

endmodule //erode_cv_xferode_patch_128_128_1_0_1_0_0_0_129_3_3_Pipeline_Col_Loop
