// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.1 (64-bit)
// Version: 2022.2.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fast_corner_detect_fast_corner_detect,hls_ip_2022_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=3.300000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.613500,HLS_SYN_LAT=38038,HLS_SYN_TPT=38036,HLS_SYN_MEM=10,HLS_SYN_DSP=0,HLS_SYN_FF=10342,HLS_SYN_LUT=14331,HLS_VERSION=2022_2_1}" *)

module fast_corner_detect (
        img_in_TDATA,
        img_out_TDATA,
        threshold,
        rows,
        cols,
        ap_clk,
        ap_rst_n,
        ap_start,
        img_in_TVALID,
        img_in_TREADY,
        img_out_TVALID,
        img_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [7:0] img_in_TDATA;
output  [7:0] img_out_TDATA;
input  [7:0] threshold;
input  [31:0] rows;
input  [31:0] cols;
input   ap_clk;
input   ap_rst_n;
input   ap_start;
input   img_in_TVALID;
output   img_in_TREADY;
output   img_out_TVALID;
input   img_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [7:0] entry_proc_U0_threshold_c_din;
wire    entry_proc_U0_threshold_c_write;
wire    Block_entry1_proc_U0_ap_start;
wire    Block_entry1_proc_U0_ap_done;
wire    Block_entry1_proc_U0_ap_continue;
wire    Block_entry1_proc_U0_ap_idle;
wire    Block_entry1_proc_U0_ap_ready;
wire    Block_entry1_proc_U0_start_out;
wire    Block_entry1_proc_U0_start_write;
wire   [31:0] Block_entry1_proc_U0_rows_c_din;
wire    Block_entry1_proc_U0_rows_c_write;
wire   [31:0] Block_entry1_proc_U0_ap_return_0;
wire   [31:0] Block_entry1_proc_U0_ap_return_1;
wire   [31:0] Block_entry1_proc_U0_ap_return_2;
wire   [31:0] Block_entry1_proc_U0_ap_return_3;
wire    ap_channel_done_imgInput_cols_c16_channel;
wire    imgInput_cols_c16_channel_full_n;
reg    ap_sync_reg_channel_write_imgInput_cols_c16_channel;
wire    ap_sync_channel_write_imgInput_cols_c16_channel;
wire    ap_channel_done_imgInput_rows_c15_channel;
wire    imgInput_rows_c15_channel_full_n;
reg    ap_sync_reg_channel_write_imgInput_rows_c15_channel;
wire    ap_sync_channel_write_imgInput_rows_c15_channel;
wire    ap_channel_done_imgOutput_cols_channel;
wire    imgOutput_cols_channel_full_n;
reg    ap_sync_reg_channel_write_imgOutput_cols_channel;
wire    ap_sync_channel_write_imgOutput_cols_channel;
wire    ap_channel_done_imgOutput_rows_channel;
wire    imgOutput_rows_channel_full_n;
reg    ap_sync_reg_channel_write_imgOutput_rows_channel;
wire    ap_sync_channel_write_imgOutput_rows_channel;
wire    Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_start;
wire    Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_done;
wire    Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_continue;
wire    Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_idle;
wire    Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready;
wire    Array2hlsStrm_8_128_128_1_1_8_16384_U0_img_in_TREADY;
wire   [7:0] Array2hlsStrm_8_128_128_1_1_8_16384_U0_stream_img_in3_din;
wire    Array2hlsStrm_8_128_128_1_1_8_16384_U0_stream_img_in3_write;
wire   [31:0] Array2hlsStrm_8_128_128_1_1_8_16384_U0_cols_c14_din;
wire    Array2hlsStrm_8_128_128_1_1_8_16384_U0_cols_c14_write;
wire    hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_start;
wire    hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_done;
wire    hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_continue;
wire    hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_idle;
wire    hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_ready;
wire    hlsStrm2xfMat_8_0_128_128_1_16384_U0_stream_img_in3_read;
wire   [7:0] hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_data1_din;
wire   [1:0] hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_data1_num_data_valid;
wire   [1:0] hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_data1_fifo_cap;
wire    hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_data1_write;
wire    hlsStrm2xfMat_8_0_128_128_1_16384_U0_dstMat_cols_align_npc_read;
wire   [31:0] hlsStrm2xfMat_8_0_128_128_1_16384_U0_cols_c13_din;
wire    hlsStrm2xfMat_8_0_128_128_1_16384_U0_cols_c13_write;
wire   [31:0] hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_rows_c_din;
wire    hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_rows_c_write;
wire   [31:0] hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_cols_c_din;
wire    hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_cols_c_write;
wire    fast_1_0_128_128_1_U0_ap_start;
wire    fast_1_0_128_128_1_U0_ap_done;
wire    fast_1_0_128_128_1_U0_ap_continue;
wire    fast_1_0_128_128_1_U0_ap_idle;
wire    fast_1_0_128_128_1_U0_ap_ready;
wire    fast_1_0_128_128_1_U0_p_src_mat_rows_read;
wire    fast_1_0_128_128_1_U0_p_src_mat_cols_read;
wire    fast_1_0_128_128_1_U0_imgInput_data1_read;
wire   [7:0] fast_1_0_128_128_1_U0_imgOutput_data2_din;
wire    fast_1_0_128_128_1_U0_imgOutput_data2_write;
wire    fast_1_0_128_128_1_U0_p_threshold_read;
wire    xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_start;
wire    xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_done;
wire    xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_continue;
wire    xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_idle;
wire    xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_ready;
wire    xfMat2hlsStrm_8_0_128_128_1_16384_U0_imgOutput_data2_read;
wire   [7:0] xfMat2hlsStrm_8_0_128_128_1_16384_U0_stream_img_out4_din;
wire    xfMat2hlsStrm_8_0_128_128_1_16384_U0_stream_img_out4_write;
wire    xfMat2hlsStrm_8_0_128_128_1_16384_U0_srcMat_cols_align_npc_read;
wire   [31:0] xfMat2hlsStrm_8_0_128_128_1_16384_U0_cols_c_din;
wire    xfMat2hlsStrm_8_0_128_128_1_16384_U0_cols_c_write;
wire    hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_start;
wire    hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_done;
wire    hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_continue;
wire    hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_idle;
wire    hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_ready;
wire    hlsStrm2Array_8_128_128_1_1_8_16384_U0_stream_img_out4_read;
wire   [7:0] hlsStrm2Array_8_128_128_1_1_8_16384_U0_img_out_TDATA;
wire    hlsStrm2Array_8_128_128_1_1_8_16384_U0_img_out_TVALID;
wire    hlsStrm2Array_8_128_128_1_1_8_16384_U0_rows_read;
wire    hlsStrm2Array_8_128_128_1_1_8_16384_U0_cols_read;
wire    threshold_c_full_n;
wire   [7:0] threshold_c_dout;
wire   [2:0] threshold_c_num_data_valid;
wire   [2:0] threshold_c_fifo_cap;
wire    threshold_c_empty_n;
wire    rows_c_full_n;
wire   [31:0] rows_c_dout;
wire   [3:0] rows_c_num_data_valid;
wire   [3:0] rows_c_fifo_cap;
wire    rows_c_empty_n;
wire   [31:0] imgOutput_rows_channel_dout;
wire   [2:0] imgOutput_rows_channel_num_data_valid;
wire   [2:0] imgOutput_rows_channel_fifo_cap;
wire    imgOutput_rows_channel_empty_n;
wire   [31:0] imgOutput_cols_channel_dout;
wire   [2:0] imgOutput_cols_channel_num_data_valid;
wire   [2:0] imgOutput_cols_channel_fifo_cap;
wire    imgOutput_cols_channel_empty_n;
wire   [31:0] imgInput_rows_c15_channel_dout;
wire   [1:0] imgInput_rows_c15_channel_num_data_valid;
wire   [1:0] imgInput_rows_c15_channel_fifo_cap;
wire    imgInput_rows_c15_channel_empty_n;
wire   [31:0] imgInput_cols_c16_channel_dout;
wire   [1:0] imgInput_cols_c16_channel_num_data_valid;
wire   [1:0] imgInput_cols_c16_channel_fifo_cap;
wire    imgInput_cols_c16_channel_empty_n;
wire    stream_img_in_full_n;
wire   [7:0] stream_img_in_dout;
wire   [1:0] stream_img_in_num_data_valid;
wire   [1:0] stream_img_in_fifo_cap;
wire    stream_img_in_empty_n;
wire    cols_c14_full_n;
wire   [31:0] cols_c14_dout;
wire   [1:0] cols_c14_num_data_valid;
wire   [1:0] cols_c14_fifo_cap;
wire    cols_c14_empty_n;
wire    imgInput_data_full_n;
wire   [7:0] imgInput_data_dout;
wire   [2:0] imgInput_data_num_data_valid;
wire   [2:0] imgInput_data_fifo_cap;
wire    imgInput_data_empty_n;
wire    cols_c13_full_n;
wire   [31:0] cols_c13_dout;
wire   [2:0] cols_c13_num_data_valid;
wire   [2:0] cols_c13_fifo_cap;
wire    cols_c13_empty_n;
wire    imgInput_rows_c_full_n;
wire   [31:0] imgInput_rows_c_dout;
wire   [1:0] imgInput_rows_c_num_data_valid;
wire   [1:0] imgInput_rows_c_fifo_cap;
wire    imgInput_rows_c_empty_n;
wire    imgInput_cols_c_full_n;
wire   [31:0] imgInput_cols_c_dout;
wire   [1:0] imgInput_cols_c_num_data_valid;
wire   [1:0] imgInput_cols_c_fifo_cap;
wire    imgInput_cols_c_empty_n;
wire    imgOutput_data_full_n;
wire   [7:0] imgOutput_data_dout;
wire   [1:0] imgOutput_data_num_data_valid;
wire   [1:0] imgOutput_data_fifo_cap;
wire    imgOutput_data_empty_n;
wire    stream_img_out_full_n;
wire   [7:0] stream_img_out_dout;
wire   [1:0] stream_img_out_num_data_valid;
wire   [1:0] stream_img_out_fifo_cap;
wire    stream_img_out_empty_n;
wire    cols_c_full_n;
wire   [31:0] cols_c_dout;
wire   [1:0] cols_c_num_data_valid;
wire   [1:0] cols_c_fifo_cap;
wire    cols_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_Block_entry1_proc_U0_ap_ready;
wire    ap_sync_Block_entry1_proc_U0_ap_ready;
reg    ap_sync_reg_Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready;
wire    ap_sync_Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready;
wire   [0:0] start_for_fast_1_0_128_128_1_U0_din;
wire    start_for_fast_1_0_128_128_1_U0_full_n;
wire   [0:0] start_for_fast_1_0_128_128_1_U0_dout;
wire    start_for_fast_1_0_128_128_1_U0_empty_n;
wire   [0:0] start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0_din;
wire    start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0_full_n;
wire   [0:0] start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0_dout;
wire    start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_imgInput_cols_c16_channel = 1'b0;
#0 ap_sync_reg_channel_write_imgInput_rows_c15_channel = 1'b0;
#0 ap_sync_reg_channel_write_imgOutput_cols_channel = 1'b0;
#0 ap_sync_reg_channel_write_imgOutput_rows_channel = 1'b0;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Block_entry1_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready = 1'b0;
end

fast_corner_detect_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_fast_1_0_128_128_1_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .threshold(threshold),
    .threshold_c_din(entry_proc_U0_threshold_c_din),
    .threshold_c_num_data_valid(threshold_c_num_data_valid),
    .threshold_c_fifo_cap(threshold_c_fifo_cap),
    .threshold_c_full_n(threshold_c_full_n),
    .threshold_c_write(entry_proc_U0_threshold_c_write)
);

fast_corner_detect_Block_entry1_proc Block_entry1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry1_proc_U0_ap_start),
    .start_full_n(start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0_full_n),
    .ap_done(Block_entry1_proc_U0_ap_done),
    .ap_continue(Block_entry1_proc_U0_ap_continue),
    .ap_idle(Block_entry1_proc_U0_ap_idle),
    .ap_ready(Block_entry1_proc_U0_ap_ready),
    .start_out(Block_entry1_proc_U0_start_out),
    .start_write(Block_entry1_proc_U0_start_write),
    .rows(rows),
    .cols(cols),
    .rows_c_din(Block_entry1_proc_U0_rows_c_din),
    .rows_c_num_data_valid(rows_c_num_data_valid),
    .rows_c_fifo_cap(rows_c_fifo_cap),
    .rows_c_full_n(rows_c_full_n),
    .rows_c_write(Block_entry1_proc_U0_rows_c_write),
    .ap_return_0(Block_entry1_proc_U0_ap_return_0),
    .ap_return_1(Block_entry1_proc_U0_ap_return_1),
    .ap_return_2(Block_entry1_proc_U0_ap_return_2),
    .ap_return_3(Block_entry1_proc_U0_ap_return_3)
);

fast_corner_detect_Array2hlsStrm_8_128_128_1_1_8_16384_s Array2hlsStrm_8_128_128_1_1_8_16384_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_start),
    .ap_done(Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_done),
    .ap_continue(Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_continue),
    .ap_idle(Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_idle),
    .ap_ready(Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready),
    .img_in_TDATA(img_in_TDATA),
    .img_in_TVALID(img_in_TVALID),
    .img_in_TREADY(Array2hlsStrm_8_128_128_1_1_8_16384_U0_img_in_TREADY),
    .stream_img_in3_din(Array2hlsStrm_8_128_128_1_1_8_16384_U0_stream_img_in3_din),
    .stream_img_in3_num_data_valid(stream_img_in_num_data_valid),
    .stream_img_in3_fifo_cap(stream_img_in_fifo_cap),
    .stream_img_in3_full_n(stream_img_in_full_n),
    .stream_img_in3_write(Array2hlsStrm_8_128_128_1_1_8_16384_U0_stream_img_in3_write),
    .rows(rows),
    .cols(cols),
    .cols_c14_din(Array2hlsStrm_8_128_128_1_1_8_16384_U0_cols_c14_din),
    .cols_c14_num_data_valid(cols_c14_num_data_valid),
    .cols_c14_fifo_cap(cols_c14_fifo_cap),
    .cols_c14_full_n(cols_c14_full_n),
    .cols_c14_write(Array2hlsStrm_8_128_128_1_1_8_16384_U0_cols_c14_write)
);

fast_corner_detect_hlsStrm2xfMat_8_0_128_128_1_16384_s hlsStrm2xfMat_8_0_128_128_1_16384_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_start),
    .ap_done(hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_done),
    .ap_continue(hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_continue),
    .ap_idle(hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_idle),
    .ap_ready(hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_ready),
    .stream_img_in3_dout(stream_img_in_dout),
    .stream_img_in3_num_data_valid(stream_img_in_num_data_valid),
    .stream_img_in3_fifo_cap(stream_img_in_fifo_cap),
    .stream_img_in3_empty_n(stream_img_in_empty_n),
    .stream_img_in3_read(hlsStrm2xfMat_8_0_128_128_1_16384_U0_stream_img_in3_read),
    .p_read(imgInput_rows_c15_channel_dout),
    .p_read1(imgInput_cols_c16_channel_dout),
    .imgInput_data1_din(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_data1_din),
    .imgInput_data1_num_data_valid(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_data1_num_data_valid),
    .imgInput_data1_fifo_cap(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_data1_fifo_cap),
    .imgInput_data1_full_n(imgInput_data_full_n),
    .imgInput_data1_write(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_data1_write),
    .dstMat_cols_align_npc_dout(cols_c14_dout),
    .dstMat_cols_align_npc_num_data_valid(cols_c14_num_data_valid),
    .dstMat_cols_align_npc_fifo_cap(cols_c14_fifo_cap),
    .dstMat_cols_align_npc_empty_n(cols_c14_empty_n),
    .dstMat_cols_align_npc_read(hlsStrm2xfMat_8_0_128_128_1_16384_U0_dstMat_cols_align_npc_read),
    .cols_c13_din(hlsStrm2xfMat_8_0_128_128_1_16384_U0_cols_c13_din),
    .cols_c13_num_data_valid(cols_c13_num_data_valid),
    .cols_c13_fifo_cap(cols_c13_fifo_cap),
    .cols_c13_full_n(cols_c13_full_n),
    .cols_c13_write(hlsStrm2xfMat_8_0_128_128_1_16384_U0_cols_c13_write),
    .imgInput_rows_c_din(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_rows_c_din),
    .imgInput_rows_c_num_data_valid(imgInput_rows_c_num_data_valid),
    .imgInput_rows_c_fifo_cap(imgInput_rows_c_fifo_cap),
    .imgInput_rows_c_full_n(imgInput_rows_c_full_n),
    .imgInput_rows_c_write(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_rows_c_write),
    .imgInput_cols_c_din(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_cols_c_din),
    .imgInput_cols_c_num_data_valid(imgInput_cols_c_num_data_valid),
    .imgInput_cols_c_fifo_cap(imgInput_cols_c_fifo_cap),
    .imgInput_cols_c_full_n(imgInput_cols_c_full_n),
    .imgInput_cols_c_write(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_cols_c_write)
);

fast_corner_detect_fast_1_0_128_128_1_s fast_1_0_128_128_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(fast_1_0_128_128_1_U0_ap_start),
    .ap_done(fast_1_0_128_128_1_U0_ap_done),
    .ap_continue(fast_1_0_128_128_1_U0_ap_continue),
    .ap_idle(fast_1_0_128_128_1_U0_ap_idle),
    .ap_ready(fast_1_0_128_128_1_U0_ap_ready),
    .p_src_mat_rows_dout(imgInput_rows_c_dout),
    .p_src_mat_rows_num_data_valid(imgInput_rows_c_num_data_valid),
    .p_src_mat_rows_fifo_cap(imgInput_rows_c_fifo_cap),
    .p_src_mat_rows_empty_n(imgInput_rows_c_empty_n),
    .p_src_mat_rows_read(fast_1_0_128_128_1_U0_p_src_mat_rows_read),
    .p_src_mat_cols_dout(imgInput_cols_c_dout),
    .p_src_mat_cols_num_data_valid(imgInput_cols_c_num_data_valid),
    .p_src_mat_cols_fifo_cap(imgInput_cols_c_fifo_cap),
    .p_src_mat_cols_empty_n(imgInput_cols_c_empty_n),
    .p_src_mat_cols_read(fast_1_0_128_128_1_U0_p_src_mat_cols_read),
    .imgInput_data1_dout(imgInput_data_dout),
    .imgInput_data1_num_data_valid(imgInput_data_num_data_valid),
    .imgInput_data1_fifo_cap(imgInput_data_fifo_cap),
    .imgInput_data1_empty_n(imgInput_data_empty_n),
    .imgInput_data1_read(fast_1_0_128_128_1_U0_imgInput_data1_read),
    .imgOutput_data2_din(fast_1_0_128_128_1_U0_imgOutput_data2_din),
    .imgOutput_data2_num_data_valid(imgOutput_data_num_data_valid),
    .imgOutput_data2_fifo_cap(imgOutput_data_fifo_cap),
    .imgOutput_data2_full_n(imgOutput_data_full_n),
    .imgOutput_data2_write(fast_1_0_128_128_1_U0_imgOutput_data2_write),
    .p_threshold_dout(threshold_c_dout),
    .p_threshold_num_data_valid(threshold_c_num_data_valid),
    .p_threshold_fifo_cap(threshold_c_fifo_cap),
    .p_threshold_empty_n(threshold_c_empty_n),
    .p_threshold_read(fast_1_0_128_128_1_U0_p_threshold_read)
);

fast_corner_detect_xfMat2hlsStrm_8_0_128_128_1_16384_s xfMat2hlsStrm_8_0_128_128_1_16384_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_start),
    .ap_done(xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_done),
    .ap_continue(xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_continue),
    .ap_idle(xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_idle),
    .ap_ready(xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_ready),
    .p_read(imgOutput_rows_channel_dout),
    .p_read1(imgOutput_cols_channel_dout),
    .imgOutput_data2_dout(imgOutput_data_dout),
    .imgOutput_data2_num_data_valid(imgOutput_data_num_data_valid),
    .imgOutput_data2_fifo_cap(imgOutput_data_fifo_cap),
    .imgOutput_data2_empty_n(imgOutput_data_empty_n),
    .imgOutput_data2_read(xfMat2hlsStrm_8_0_128_128_1_16384_U0_imgOutput_data2_read),
    .stream_img_out4_din(xfMat2hlsStrm_8_0_128_128_1_16384_U0_stream_img_out4_din),
    .stream_img_out4_num_data_valid(stream_img_out_num_data_valid),
    .stream_img_out4_fifo_cap(stream_img_out_fifo_cap),
    .stream_img_out4_full_n(stream_img_out_full_n),
    .stream_img_out4_write(xfMat2hlsStrm_8_0_128_128_1_16384_U0_stream_img_out4_write),
    .srcMat_cols_align_npc_dout(cols_c13_dout),
    .srcMat_cols_align_npc_num_data_valid(cols_c13_num_data_valid),
    .srcMat_cols_align_npc_fifo_cap(cols_c13_fifo_cap),
    .srcMat_cols_align_npc_empty_n(cols_c13_empty_n),
    .srcMat_cols_align_npc_read(xfMat2hlsStrm_8_0_128_128_1_16384_U0_srcMat_cols_align_npc_read),
    .cols_c_din(xfMat2hlsStrm_8_0_128_128_1_16384_U0_cols_c_din),
    .cols_c_num_data_valid(cols_c_num_data_valid),
    .cols_c_fifo_cap(cols_c_fifo_cap),
    .cols_c_full_n(cols_c_full_n),
    .cols_c_write(xfMat2hlsStrm_8_0_128_128_1_16384_U0_cols_c_write)
);

fast_corner_detect_hlsStrm2Array_8_128_128_1_1_8_16384_s hlsStrm2Array_8_128_128_1_1_8_16384_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_start),
    .ap_done(hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_done),
    .ap_continue(hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_continue),
    .ap_idle(hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_idle),
    .ap_ready(hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_ready),
    .stream_img_out4_dout(stream_img_out_dout),
    .stream_img_out4_num_data_valid(stream_img_out_num_data_valid),
    .stream_img_out4_fifo_cap(stream_img_out_fifo_cap),
    .stream_img_out4_empty_n(stream_img_out_empty_n),
    .stream_img_out4_read(hlsStrm2Array_8_128_128_1_1_8_16384_U0_stream_img_out4_read),
    .img_out_TDATA(hlsStrm2Array_8_128_128_1_1_8_16384_U0_img_out_TDATA),
    .img_out_TVALID(hlsStrm2Array_8_128_128_1_1_8_16384_U0_img_out_TVALID),
    .img_out_TREADY(img_out_TREADY),
    .rows_dout(rows_c_dout),
    .rows_num_data_valid(rows_c_num_data_valid),
    .rows_fifo_cap(rows_c_fifo_cap),
    .rows_empty_n(rows_c_empty_n),
    .rows_read(hlsStrm2Array_8_128_128_1_1_8_16384_U0_rows_read),
    .cols_dout(cols_c_dout),
    .cols_num_data_valid(cols_c_num_data_valid),
    .cols_fifo_cap(cols_c_fifo_cap),
    .cols_empty_n(cols_c_empty_n),
    .cols_read(hlsStrm2Array_8_128_128_1_1_8_16384_U0_cols_read)
);

fast_corner_detect_fifo_w8_d4_S threshold_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_threshold_c_din),
    .if_full_n(threshold_c_full_n),
    .if_write(entry_proc_U0_threshold_c_write),
    .if_dout(threshold_c_dout),
    .if_num_data_valid(threshold_c_num_data_valid),
    .if_fifo_cap(threshold_c_fifo_cap),
    .if_empty_n(threshold_c_empty_n),
    .if_read(fast_1_0_128_128_1_U0_p_threshold_read)
);

fast_corner_detect_fifo_w32_d5_S rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_rows_c_din),
    .if_full_n(rows_c_full_n),
    .if_write(Block_entry1_proc_U0_rows_c_write),
    .if_dout(rows_c_dout),
    .if_num_data_valid(rows_c_num_data_valid),
    .if_fifo_cap(rows_c_fifo_cap),
    .if_empty_n(rows_c_empty_n),
    .if_read(hlsStrm2Array_8_128_128_1_1_8_16384_U0_rows_read)
);

fast_corner_detect_fifo_w32_d4_S imgOutput_rows_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_0),
    .if_full_n(imgOutput_rows_channel_full_n),
    .if_write(ap_channel_done_imgOutput_rows_channel),
    .if_dout(imgOutput_rows_channel_dout),
    .if_num_data_valid(imgOutput_rows_channel_num_data_valid),
    .if_fifo_cap(imgOutput_rows_channel_fifo_cap),
    .if_empty_n(imgOutput_rows_channel_empty_n),
    .if_read(xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_ready)
);

fast_corner_detect_fifo_w32_d4_S imgOutput_cols_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_1),
    .if_full_n(imgOutput_cols_channel_full_n),
    .if_write(ap_channel_done_imgOutput_cols_channel),
    .if_dout(imgOutput_cols_channel_dout),
    .if_num_data_valid(imgOutput_cols_channel_num_data_valid),
    .if_fifo_cap(imgOutput_cols_channel_fifo_cap),
    .if_empty_n(imgOutput_cols_channel_empty_n),
    .if_read(xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_ready)
);

fast_corner_detect_fifo_w32_d2_S imgInput_rows_c15_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_2),
    .if_full_n(imgInput_rows_c15_channel_full_n),
    .if_write(ap_channel_done_imgInput_rows_c15_channel),
    .if_dout(imgInput_rows_c15_channel_dout),
    .if_num_data_valid(imgInput_rows_c15_channel_num_data_valid),
    .if_fifo_cap(imgInput_rows_c15_channel_fifo_cap),
    .if_empty_n(imgInput_rows_c15_channel_empty_n),
    .if_read(hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_ready)
);

fast_corner_detect_fifo_w32_d2_S imgInput_cols_c16_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_3),
    .if_full_n(imgInput_cols_c16_channel_full_n),
    .if_write(ap_channel_done_imgInput_cols_c16_channel),
    .if_dout(imgInput_cols_c16_channel_dout),
    .if_num_data_valid(imgInput_cols_c16_channel_num_data_valid),
    .if_fifo_cap(imgInput_cols_c16_channel_fifo_cap),
    .if_empty_n(imgInput_cols_c16_channel_empty_n),
    .if_read(hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_ready)
);

fast_corner_detect_fifo_w8_d2_S_x stream_img_in_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Array2hlsStrm_8_128_128_1_1_8_16384_U0_stream_img_in3_din),
    .if_full_n(stream_img_in_full_n),
    .if_write(Array2hlsStrm_8_128_128_1_1_8_16384_U0_stream_img_in3_write),
    .if_dout(stream_img_in_dout),
    .if_num_data_valid(stream_img_in_num_data_valid),
    .if_fifo_cap(stream_img_in_fifo_cap),
    .if_empty_n(stream_img_in_empty_n),
    .if_read(hlsStrm2xfMat_8_0_128_128_1_16384_U0_stream_img_in3_read)
);

fast_corner_detect_fifo_w32_d2_S cols_c14_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Array2hlsStrm_8_128_128_1_1_8_16384_U0_cols_c14_din),
    .if_full_n(cols_c14_full_n),
    .if_write(Array2hlsStrm_8_128_128_1_1_8_16384_U0_cols_c14_write),
    .if_dout(cols_c14_dout),
    .if_num_data_valid(cols_c14_num_data_valid),
    .if_fifo_cap(cols_c14_fifo_cap),
    .if_empty_n(cols_c14_empty_n),
    .if_read(hlsStrm2xfMat_8_0_128_128_1_16384_U0_dstMat_cols_align_npc_read)
);

fast_corner_detect_fifo_w8_d3_S imgInput_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_data1_din),
    .if_full_n(imgInput_data_full_n),
    .if_write(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_data1_write),
    .if_dout(imgInput_data_dout),
    .if_num_data_valid(imgInput_data_num_data_valid),
    .if_fifo_cap(imgInput_data_fifo_cap),
    .if_empty_n(imgInput_data_empty_n),
    .if_read(fast_1_0_128_128_1_U0_imgInput_data1_read)
);

fast_corner_detect_fifo_w32_d3_S cols_c13_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hlsStrm2xfMat_8_0_128_128_1_16384_U0_cols_c13_din),
    .if_full_n(cols_c13_full_n),
    .if_write(hlsStrm2xfMat_8_0_128_128_1_16384_U0_cols_c13_write),
    .if_dout(cols_c13_dout),
    .if_num_data_valid(cols_c13_num_data_valid),
    .if_fifo_cap(cols_c13_fifo_cap),
    .if_empty_n(cols_c13_empty_n),
    .if_read(xfMat2hlsStrm_8_0_128_128_1_16384_U0_srcMat_cols_align_npc_read)
);

fast_corner_detect_fifo_w32_d2_S imgInput_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_rows_c_din),
    .if_full_n(imgInput_rows_c_full_n),
    .if_write(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_rows_c_write),
    .if_dout(imgInput_rows_c_dout),
    .if_num_data_valid(imgInput_rows_c_num_data_valid),
    .if_fifo_cap(imgInput_rows_c_fifo_cap),
    .if_empty_n(imgInput_rows_c_empty_n),
    .if_read(fast_1_0_128_128_1_U0_p_src_mat_rows_read)
);

fast_corner_detect_fifo_w32_d2_S imgInput_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_cols_c_din),
    .if_full_n(imgInput_cols_c_full_n),
    .if_write(hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_cols_c_write),
    .if_dout(imgInput_cols_c_dout),
    .if_num_data_valid(imgInput_cols_c_num_data_valid),
    .if_fifo_cap(imgInput_cols_c_fifo_cap),
    .if_empty_n(imgInput_cols_c_empty_n),
    .if_read(fast_1_0_128_128_1_U0_p_src_mat_cols_read)
);

fast_corner_detect_fifo_w8_d2_S_x imgOutput_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fast_1_0_128_128_1_U0_imgOutput_data2_din),
    .if_full_n(imgOutput_data_full_n),
    .if_write(fast_1_0_128_128_1_U0_imgOutput_data2_write),
    .if_dout(imgOutput_data_dout),
    .if_num_data_valid(imgOutput_data_num_data_valid),
    .if_fifo_cap(imgOutput_data_fifo_cap),
    .if_empty_n(imgOutput_data_empty_n),
    .if_read(xfMat2hlsStrm_8_0_128_128_1_16384_U0_imgOutput_data2_read)
);

fast_corner_detect_fifo_w8_d2_S_x stream_img_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xfMat2hlsStrm_8_0_128_128_1_16384_U0_stream_img_out4_din),
    .if_full_n(stream_img_out_full_n),
    .if_write(xfMat2hlsStrm_8_0_128_128_1_16384_U0_stream_img_out4_write),
    .if_dout(stream_img_out_dout),
    .if_num_data_valid(stream_img_out_num_data_valid),
    .if_fifo_cap(stream_img_out_fifo_cap),
    .if_empty_n(stream_img_out_empty_n),
    .if_read(hlsStrm2Array_8_128_128_1_1_8_16384_U0_stream_img_out4_read)
);

fast_corner_detect_fifo_w32_d2_S cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xfMat2hlsStrm_8_0_128_128_1_16384_U0_cols_c_din),
    .if_full_n(cols_c_full_n),
    .if_write(xfMat2hlsStrm_8_0_128_128_1_16384_U0_cols_c_write),
    .if_dout(cols_c_dout),
    .if_num_data_valid(cols_c_num_data_valid),
    .if_fifo_cap(cols_c_fifo_cap),
    .if_empty_n(cols_c_empty_n),
    .if_read(hlsStrm2Array_8_128_128_1_1_8_16384_U0_cols_read)
);

fast_corner_detect_start_for_fast_1_0_128_128_1_U0 start_for_fast_1_0_128_128_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fast_1_0_128_128_1_U0_din),
    .if_full_n(start_for_fast_1_0_128_128_1_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_fast_1_0_128_128_1_U0_dout),
    .if_empty_n(start_for_fast_1_0_128_128_1_U0_empty_n),
    .if_read(fast_1_0_128_128_1_U0_ap_ready)
);

fast_corner_detect_start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0 start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0_din),
    .if_full_n(start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0_full_n),
    .if_write(Block_entry1_proc_U0_start_write),
    .if_dout(start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0_dout),
    .if_empty_n(start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0_empty_n),
    .if_read(hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready <= ap_sync_Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_entry1_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_entry1_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_entry1_proc_U0_ap_ready <= ap_sync_Block_entry1_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_imgInput_cols_c16_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_imgInput_cols_c16_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_imgInput_cols_c16_channel <= ap_sync_channel_write_imgInput_cols_c16_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_imgInput_rows_c15_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_imgInput_rows_c15_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_imgInput_rows_c15_channel <= ap_sync_channel_write_imgInput_rows_c15_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_imgOutput_cols_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_imgOutput_cols_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_imgOutput_cols_channel <= ap_sync_channel_write_imgOutput_cols_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_imgOutput_rows_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_imgOutput_rows_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_imgOutput_rows_channel <= ap_sync_channel_write_imgOutput_rows_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_continue = 1'b1;

assign Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_start = ((ap_sync_reg_Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_entry1_proc_U0_ap_continue = (ap_sync_channel_write_imgOutput_rows_channel & ap_sync_channel_write_imgOutput_cols_channel & ap_sync_channel_write_imgInput_rows_c15_channel & ap_sync_channel_write_imgInput_cols_c16_channel);

assign Block_entry1_proc_U0_ap_start = ((ap_sync_reg_Block_entry1_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign ap_channel_done_imgInput_cols_c16_channel = ((ap_sync_reg_channel_write_imgInput_cols_c16_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_imgInput_rows_c15_channel = ((ap_sync_reg_channel_write_imgInput_rows_c15_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_imgOutput_cols_channel = ((ap_sync_reg_channel_write_imgOutput_cols_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_imgOutput_rows_channel = ((ap_sync_reg_channel_write_imgOutput_rows_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_done = hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_done;

assign ap_idle = (xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_idle & hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_idle & hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_idle & fast_1_0_128_128_1_U0_ap_idle & (imgInput_cols_c16_channel_empty_n ^ 1'b1) & (imgInput_rows_c15_channel_empty_n ^ 1'b1) & (imgOutput_cols_channel_empty_n ^ 1'b1) & (imgOutput_rows_channel_empty_n ^ 1'b1) & entry_proc_U0_ap_idle & Block_entry1_proc_U0_ap_idle & Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready = (ap_sync_reg_Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready | Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready);

assign ap_sync_Block_entry1_proc_U0_ap_ready = (ap_sync_reg_Block_entry1_proc_U0_ap_ready | Block_entry1_proc_U0_ap_ready);

assign ap_sync_channel_write_imgInput_cols_c16_channel = ((imgInput_cols_c16_channel_full_n & ap_channel_done_imgInput_cols_c16_channel) | ap_sync_reg_channel_write_imgInput_cols_c16_channel);

assign ap_sync_channel_write_imgInput_rows_c15_channel = ((imgInput_rows_c15_channel_full_n & ap_channel_done_imgInput_rows_c15_channel) | ap_sync_reg_channel_write_imgInput_rows_c15_channel);

assign ap_sync_channel_write_imgOutput_cols_channel = ((imgOutput_cols_channel_full_n & ap_channel_done_imgOutput_cols_channel) | ap_sync_reg_channel_write_imgOutput_cols_channel);

assign ap_sync_channel_write_imgOutput_rows_channel = ((imgOutput_rows_channel_full_n & ap_channel_done_imgOutput_rows_channel) | ap_sync_reg_channel_write_imgOutput_rows_channel);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_Block_entry1_proc_U0_ap_ready & ap_sync_Array2hlsStrm_8_128_128_1_1_8_16384_U0_ap_ready);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign fast_1_0_128_128_1_U0_ap_continue = 1'b1;

assign fast_1_0_128_128_1_U0_ap_start = start_for_fast_1_0_128_128_1_U0_empty_n;

assign hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_continue = 1'b1;

assign hlsStrm2Array_8_128_128_1_1_8_16384_U0_ap_start = start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0_empty_n;

assign hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_continue = 1'b1;

assign hlsStrm2xfMat_8_0_128_128_1_16384_U0_ap_start = (imgInput_rows_c15_channel_empty_n & imgInput_cols_c16_channel_empty_n);

assign hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_data1_fifo_cap = imgInput_data_fifo_cap;

assign hlsStrm2xfMat_8_0_128_128_1_16384_U0_imgInput_data1_num_data_valid = imgInput_data_num_data_valid;

assign img_in_TREADY = Array2hlsStrm_8_128_128_1_1_8_16384_U0_img_in_TREADY;

assign img_out_TDATA = hlsStrm2Array_8_128_128_1_1_8_16384_U0_img_out_TDATA;

assign img_out_TVALID = hlsStrm2Array_8_128_128_1_1_8_16384_U0_img_out_TVALID;

assign start_for_fast_1_0_128_128_1_U0_din = 1'b1;

assign start_for_hlsStrm2Array_8_128_128_1_1_8_16384_U0_din = 1'b1;

assign xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_continue = 1'b1;

assign xfMat2hlsStrm_8_0_128_128_1_16384_U0_ap_start = (imgOutput_rows_channel_empty_n & imgOutput_cols_channel_empty_n);

endmodule //fast_corner_detect
