// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.1 (64-bit)
// Version: 2022.2.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgInput_data1_dout,
        imgInput_data1_num_data_valid,
        imgInput_data1_fifo_cap,
        imgInput_data1_empty_n,
        imgInput_data1_read,
        p_dst_data1_din,
        p_dst_data1_num_data_valid,
        p_dst_data1_fifo_cap,
        p_dst_data1_full_n,
        p_dst_data1_write,
        img_height,
        img_width,
        p_threshold,
        p_image_height_c_din,
        p_image_height_c_num_data_valid,
        p_image_height_c_fifo_cap,
        p_image_height_c_full_n,
        p_image_height_c_write,
        p_image_width_c_din,
        p_image_width_c_num_data_valid,
        p_image_width_c_fifo_cap,
        p_image_width_c_full_n,
        p_image_width_c_write
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] imgInput_data1_dout;
input  [2:0] imgInput_data1_num_data_valid;
input  [2:0] imgInput_data1_fifo_cap;
input   imgInput_data1_empty_n;
output   imgInput_data1_read;
output  [7:0] p_dst_data1_din;
input  [1:0] p_dst_data1_num_data_valid;
input  [1:0] p_dst_data1_fifo_cap;
input   p_dst_data1_full_n;
output   p_dst_data1_write;
input  [15:0] img_height;
input  [15:0] img_width;
input  [7:0] p_threshold;
output  [15:0] p_image_height_c_din;
input  [1:0] p_image_height_c_num_data_valid;
input  [1:0] p_image_height_c_fifo_cap;
input   p_image_height_c_full_n;
output   p_image_height_c_write;
output  [15:0] p_image_width_c_din;
input  [1:0] p_image_width_c_num_data_valid;
input  [1:0] p_image_width_c_fifo_cap;
input   p_image_width_c_full_n;
output   p_image_width_c_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg imgInput_data1_read;
reg p_dst_data1_write;
reg p_image_height_c_write;
reg p_image_width_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    p_image_height_c_blk_n;
reg    p_image_width_c_blk_n;
wire   [13:0] empty_fu_323_p1;
reg   [13:0] empty_reg_770;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln506_fu_352_p1;
reg   [63:0] zext_ln506_reg_803;
wire   [2:0] empty_37_fu_369_p1;
reg   [2:0] empty_37_reg_811;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln1027_fu_364_p2;
wire   [16:0] add_i_i66_fu_420_p2;
reg   [16:0] add_i_i66_reg_877;
wire    ap_CS_fsm_state8;
wire   [13:0] op2_assign_fu_426_p2;
reg   [13:0] op2_assign_reg_882;
wire   [16:0] sub350_i_fu_431_p2;
reg   [16:0] sub350_i_reg_887;
wire   [8:0] b0_fu_440_p2;
reg   [8:0] b0_reg_893;
reg   [12:0] row_ind_V_25_reg_898;
wire    ap_CS_fsm_state9;
reg   [12:0] row_ind_V_26_reg_905;
reg   [12:0] row_ind_V_27_reg_911;
reg   [12:0] row_ind_V_28_reg_917;
reg   [12:0] row_ind_V_29_reg_923;
reg   [12:0] row_ind_V_30_reg_929;
wire   [0:0] cmp_i_i381_i_fu_480_p2;
reg   [0:0] cmp_i_i381_i_reg_937;
wire   [0:0] icmp_ln1027_3_fu_475_p2;
wire   [0:0] cmp_i_i329_i_fu_485_p2;
reg   [0:0] cmp_i_i329_i_reg_942;
wire  signed [16:0] sub_i_i297_i_fu_490_p2;
reg  signed [16:0] sub_i_i297_i_reg_953;
wire   [0:0] ult_fu_495_p2;
reg   [0:0] ult_reg_959;
wire   [0:0] cmp_i_i73_i_not_fu_500_p2;
reg   [0:0] cmp_i_i73_i_not_reg_964;
wire   [0:0] spec_select484_fu_559_p2;
reg   [0:0] spec_select484_reg_970;
wire    ap_CS_fsm_state10;
wire   [0:0] spec_select488_fu_570_p2;
reg   [0:0] spec_select488_reg_975;
wire   [0:0] spec_select492_fu_591_p2;
reg   [0:0] spec_select492_reg_980;
wire   [0:0] spec_select496_fu_602_p2;
reg   [0:0] spec_select496_reg_985;
wire   [0:0] spec_select500_fu_623_p2;
reg   [0:0] spec_select500_reg_990;
wire   [0:0] spec_select504_fu_634_p2;
reg   [0:0] spec_select504_reg_995;
wire   [0:0] spec_select508_fu_644_p2;
reg   [0:0] spec_select508_reg_1000;
wire   [2:0] empty_39_fu_649_p1;
reg   [2:0] empty_39_reg_1005;
reg   [12:0] row_ind_V_load_reg_1010;
wire    ap_CS_fsm_state11;
wire   [0:0] rev155_fu_657_p2;
reg   [0:0] rev155_reg_1015;
wire   [2:0] empty_40_fu_663_p1;
reg   [2:0] empty_40_reg_1020;
wire   [2:0] empty_41_fu_668_p1;
reg   [2:0] empty_41_reg_1025;
wire   [2:0] empty_42_fu_672_p1;
reg   [2:0] empty_42_reg_1030;
wire   [2:0] empty_43_fu_676_p1;
reg   [2:0] empty_43_reg_1035;
wire   [2:0] empty_44_fu_680_p1;
reg   [2:0] empty_44_reg_1040;
wire   [2:0] empty_45_fu_684_p1;
reg   [2:0] empty_45_reg_1045;
wire   [2:0] empty_46_fu_688_p1;
reg   [2:0] empty_46_reg_1050;
wire   [0:0] xor_ln425_fu_692_p2;
reg   [0:0] xor_ln425_reg_1055;
reg    buf_V_ce0;
wire   [7:0] buf_V_q0;
reg   [6:0] buf_V_address1;
reg    buf_V_ce1;
reg    buf_V_we1;
reg   [7:0] buf_V_d1;
reg    buf_V_3_ce0;
wire   [7:0] buf_V_3_q0;
reg   [6:0] buf_V_3_address1;
reg    buf_V_3_ce1;
reg    buf_V_3_we1;
reg   [7:0] buf_V_3_d1;
reg    buf_V_4_ce0;
wire   [7:0] buf_V_4_q0;
reg   [6:0] buf_V_4_address1;
reg    buf_V_4_ce1;
reg    buf_V_4_we1;
reg   [7:0] buf_V_4_d1;
reg    buf_V_5_ce0;
wire   [7:0] buf_V_5_q0;
reg   [6:0] buf_V_5_address1;
reg    buf_V_5_ce1;
reg    buf_V_5_we1;
reg   [7:0] buf_V_5_d1;
reg    buf_V_6_ce0;
wire   [7:0] buf_V_6_q0;
reg   [6:0] buf_V_6_address1;
reg    buf_V_6_ce1;
reg    buf_V_6_we1;
reg   [7:0] buf_V_6_d1;
reg    buf_V_7_ce0;
wire   [7:0] buf_V_7_q0;
reg   [6:0] buf_V_7_address1;
reg    buf_V_7_ce1;
reg    buf_V_7_we1;
reg   [7:0] buf_V_7_d1;
reg    buf_V_8_ce0;
wire   [7:0] buf_V_8_q0;
reg   [6:0] buf_V_8_address1;
reg    buf_V_8_ce1;
reg    buf_V_8_we1;
reg   [7:0] buf_V_8_d1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_start;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_done;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_idle;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_ready;
wire   [12:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_15_out;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_15_out_ap_vld;
wire   [12:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_14_out;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_14_out_ap_vld;
wire   [12:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_13_out;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_13_out_ap_vld;
wire   [12:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_12_out;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_12_out_ap_vld;
wire   [12:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_11_out;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_11_out_ap_vld;
wire   [12:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_10_out;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_10_out_ap_vld;
wire   [12:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_out;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_out_ap_vld;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_start;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_done;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_idle;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_ready;
wire   [1:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_imgInput_data1_num_data_valid;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_imgInput_data1_read;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_8_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_8_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_8_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_8_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_7_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_7_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_7_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_7_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_6_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_6_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_6_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_6_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_5_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_5_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_5_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_5_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_4_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_4_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_4_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_4_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_3_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_3_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_3_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_3_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_d1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_start;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_done;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_idle;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_ready;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_3_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_3_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_3_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_3_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_4_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_4_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_4_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_4_d1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_start;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_done;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_idle;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_ready;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_imgInput_data1_read;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_p_dst_data1_din;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_p_dst_data1_write;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_address0;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_ce0;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_address0;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_ce0;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_address0;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_ce0;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_address0;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_ce0;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_address0;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_ce0;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_address0;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_ce0;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_d1;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_address0;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_ce0;
wire   [6:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_address1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_ce1;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_we1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_d1;
wire   [7:0] grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_p_0_0_01084242_out_o;
wire    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_p_0_0_01084242_out_o_ap_vld;
reg    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_start_reg;
reg    ap_block_state1_ignore_call32;
wire    ap_CS_fsm_state2;
reg    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_start_reg;
wire    ap_CS_fsm_state12;
reg   [7:0] p_0_0_010842_lcssa550_fu_172;
reg   [63:0] init_buf_fu_112;
wire   [63:0] add_ln506_fu_373_p2;
wire   [63:0] zext_ln541_fu_348_p1;
reg   [12:0] row_V_fu_176;
wire   [12:0] row_V_5_fu_506_p2;
reg   [12:0] row_ind_V_fu_180;
reg   [12:0] row_ind_V_19_fu_184;
reg   [12:0] row_ind_V_20_fu_188;
reg   [12:0] row_ind_V_21_fu_192;
reg   [12:0] row_ind_V_22_fu_196;
reg   [12:0] row_ind_V_23_fu_200;
reg   [12:0] row_ind_V_24_fu_204;
reg    ap_block_state1;
wire   [16:0] conv3_i_i_i61_fu_417_p1;
wire   [8:0] p_threshold_cast_fu_437_p1;
wire   [16:0] zext_ln1027_3_fu_471_p1;
wire   [15:0] zext_ln1027_fu_467_p1;
wire  signed [17:0] sub_i_i297_i_cast_fu_542_p1;
wire   [17:0] sub_i273_i_fu_545_p2;
wire   [0:0] tmp_fu_551_p3;
wire   [0:0] cmp_i_i253_i_1_fu_564_p2;
wire   [16:0] tmp_2_fu_575_p4;
wire   [0:0] icmp_fu_585_p2;
wire   [0:0] cmp_i_i253_i_3_fu_596_p2;
wire   [15:0] tmp_3_fu_607_p4;
wire   [0:0] icmp154_fu_617_p2;
wire   [0:0] cmp_i_i253_i_5_fu_628_p2;
wire   [0:0] cmp_i_i253_i_6_fu_639_p2;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 12'd1;
#0 grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_start_reg = 1'b0;
#0 grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_start_reg = 1'b0;
#0 grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_start_reg = 1'b0;
#0 grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_start_reg = 1'b0;
end

fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3_buf_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_address0),
    .ce0(buf_V_ce0),
    .q0(buf_V_q0),
    .address1(buf_V_address1),
    .ce1(buf_V_ce1),
    .we1(buf_V_we1),
    .d1(buf_V_d1)
);

fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3_buf_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
buf_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_address0),
    .ce0(buf_V_3_ce0),
    .q0(buf_V_3_q0),
    .address1(buf_V_3_address1),
    .ce1(buf_V_3_ce1),
    .we1(buf_V_3_we1),
    .d1(buf_V_3_d1)
);

fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3_buf_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
buf_V_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_address0),
    .ce0(buf_V_4_ce0),
    .q0(buf_V_4_q0),
    .address1(buf_V_4_address1),
    .ce1(buf_V_4_ce1),
    .we1(buf_V_4_we1),
    .d1(buf_V_4_d1)
);

fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3_buf_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
buf_V_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_address0),
    .ce0(buf_V_5_ce0),
    .q0(buf_V_5_q0),
    .address1(buf_V_5_address1),
    .ce1(buf_V_5_ce1),
    .we1(buf_V_5_we1),
    .d1(buf_V_5_d1)
);

fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3_buf_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
buf_V_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_address0),
    .ce0(buf_V_6_ce0),
    .q0(buf_V_6_q0),
    .address1(buf_V_6_address1),
    .ce1(buf_V_6_ce1),
    .we1(buf_V_6_we1),
    .d1(buf_V_6_d1)
);

fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3_buf_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
buf_V_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_address0),
    .ce0(buf_V_7_ce0),
    .q0(buf_V_7_q0),
    .address1(buf_V_7_address1),
    .ce1(buf_V_7_ce1),
    .we1(buf_V_7_we1),
    .d1(buf_V_7_d1)
);

fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3_buf_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
buf_V_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_address0),
    .ce0(buf_V_8_ce0),
    .q0(buf_V_8_q0),
    .address1(buf_V_8_address1),
    .ce1(buf_V_8_ce1),
    .we1(buf_V_8_we1),
    .d1(buf_V_8_d1)
);

fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1 grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_start),
    .ap_done(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_done),
    .ap_idle(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_idle),
    .ap_ready(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_ready),
    .row_ind_V_15_out(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_15_out),
    .row_ind_V_15_out_ap_vld(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_15_out_ap_vld),
    .row_ind_V_14_out(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_14_out),
    .row_ind_V_14_out_ap_vld(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_14_out_ap_vld),
    .row_ind_V_13_out(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_13_out),
    .row_ind_V_13_out_ap_vld(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_13_out_ap_vld),
    .row_ind_V_12_out(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_12_out),
    .row_ind_V_12_out_ap_vld(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_12_out_ap_vld),
    .row_ind_V_11_out(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_11_out),
    .row_ind_V_11_out_ap_vld(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_11_out_ap_vld),
    .row_ind_V_10_out(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_10_out),
    .row_ind_V_10_out_ap_vld(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_10_out_ap_vld),
    .row_ind_V_out(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_out),
    .row_ind_V_out_ap_vld(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_out_ap_vld)
);

fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2 grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_start),
    .ap_done(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_done),
    .ap_idle(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_idle),
    .ap_ready(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_ready),
    .imgInput_data1_dout(imgInput_data1_dout),
    .imgInput_data1_num_data_valid(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_imgInput_data1_num_data_valid),
    .imgInput_data1_fifo_cap(2'd0),
    .imgInput_data1_empty_n(imgInput_data1_empty_n),
    .imgInput_data1_read(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_imgInput_data1_read),
    .img_width(img_width),
    .buf_V_8_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_8_address1),
    .buf_V_8_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_8_ce1),
    .buf_V_8_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_8_we1),
    .buf_V_8_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_8_d1),
    .buf_V_7_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_7_address1),
    .buf_V_7_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_7_ce1),
    .buf_V_7_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_7_we1),
    .buf_V_7_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_7_d1),
    .buf_V_6_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_6_address1),
    .buf_V_6_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_6_ce1),
    .buf_V_6_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_6_we1),
    .buf_V_6_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_6_d1),
    .buf_V_5_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_5_address1),
    .buf_V_5_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_5_ce1),
    .buf_V_5_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_5_we1),
    .buf_V_5_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_5_d1),
    .buf_V_4_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_4_address1),
    .buf_V_4_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_4_ce1),
    .buf_V_4_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_4_we1),
    .buf_V_4_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_4_d1),
    .buf_V_3_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_3_address1),
    .buf_V_3_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_3_ce1),
    .buf_V_3_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_3_we1),
    .buf_V_3_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_3_d1),
    .buf_V_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_address1),
    .buf_V_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_ce1),
    .buf_V_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_we1),
    .buf_V_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_d1),
    .init_buf_cast(empty_37_reg_811)
);

fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3 grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_start),
    .ap_done(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_done),
    .ap_idle(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_idle),
    .ap_ready(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_ready),
    .img_width(img_width),
    .buf_V_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_address1),
    .buf_V_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_ce1),
    .buf_V_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_we1),
    .buf_V_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_d1),
    .buf_V_3_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_3_address1),
    .buf_V_3_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_3_ce1),
    .buf_V_3_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_3_we1),
    .buf_V_3_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_3_d1),
    .buf_V_4_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_4_address1),
    .buf_V_4_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_4_ce1),
    .buf_V_4_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_4_we1),
    .buf_V_4_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_4_d1)
);

fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_start),
    .ap_done(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_done),
    .ap_idle(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_idle),
    .ap_ready(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_ready),
    .imgInput_data1_dout(imgInput_data1_dout),
    .imgInput_data1_num_data_valid(imgInput_data1_num_data_valid),
    .imgInput_data1_fifo_cap(2'd0),
    .imgInput_data1_empty_n(imgInput_data1_empty_n),
    .imgInput_data1_read(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_imgInput_data1_read),
    .p_dst_data1_din(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_p_dst_data1_din),
    .p_dst_data1_num_data_valid(2'd0),
    .p_dst_data1_fifo_cap(2'd0),
    .p_dst_data1_full_n(p_dst_data1_full_n),
    .p_dst_data1_write(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_p_dst_data1_write),
    .op2_assign(op2_assign_reg_882),
    .buf_V_8_address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_address0),
    .buf_V_8_ce0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_ce0),
    .buf_V_8_q0(buf_V_8_q0),
    .buf_V_8_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_address1),
    .buf_V_8_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_ce1),
    .buf_V_8_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_we1),
    .buf_V_8_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_d1),
    .buf_V_address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_address0),
    .buf_V_ce0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_ce0),
    .buf_V_q0(buf_V_q0),
    .buf_V_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_address1),
    .buf_V_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_ce1),
    .buf_V_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_we1),
    .buf_V_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_d1),
    .buf_V_3_address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_address0),
    .buf_V_3_ce0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_ce0),
    .buf_V_3_q0(buf_V_3_q0),
    .buf_V_3_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_address1),
    .buf_V_3_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_ce1),
    .buf_V_3_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_we1),
    .buf_V_3_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_d1),
    .buf_V_4_address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_address0),
    .buf_V_4_ce0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_ce0),
    .buf_V_4_q0(buf_V_4_q0),
    .buf_V_4_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_address1),
    .buf_V_4_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_ce1),
    .buf_V_4_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_we1),
    .buf_V_4_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_d1),
    .buf_V_5_address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_address0),
    .buf_V_5_ce0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_ce0),
    .buf_V_5_q0(buf_V_5_q0),
    .buf_V_5_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_address1),
    .buf_V_5_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_ce1),
    .buf_V_5_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_we1),
    .buf_V_5_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_d1),
    .buf_V_6_address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_address0),
    .buf_V_6_ce0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_ce0),
    .buf_V_6_q0(buf_V_6_q0),
    .buf_V_6_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_address1),
    .buf_V_6_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_ce1),
    .buf_V_6_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_we1),
    .buf_V_6_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_d1),
    .buf_V_7_address0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_address0),
    .buf_V_7_ce0(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_ce0),
    .buf_V_7_q0(buf_V_7_q0),
    .buf_V_7_address1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_address1),
    .buf_V_7_ce1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_ce1),
    .buf_V_7_we1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_we1),
    .buf_V_7_d1(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_d1),
    .row_ind_V_24(row_ind_V_load_reg_1010),
    .row_ind_V_25(row_ind_V_25_reg_898),
    .row_ind_V_26(row_ind_V_26_reg_905),
    .row_ind_V_27(row_ind_V_27_reg_911),
    .row_ind_V_28(row_ind_V_28_reg_917),
    .row_ind_V_29(row_ind_V_29_reg_923),
    .row_ind_V_30(row_ind_V_30_reg_929),
    .sub_i273_i_cast(empty_39_reg_1005),
    .row_ind_V_24_cast(empty_40_reg_1020),
    .spec_select484(spec_select484_reg_970),
    .row_ind_V_25_cast(empty_41_reg_1025),
    .spec_select488(spec_select488_reg_975),
    .row_ind_V_26_cast(empty_42_reg_1030),
    .spec_select492(spec_select492_reg_980),
    .row_ind_V_27_cast(empty_43_reg_1035),
    .spec_select496(spec_select496_reg_985),
    .row_ind_V_28_cast(empty_44_reg_1040),
    .spec_select500(spec_select500_reg_990),
    .row_ind_V_29_cast(empty_45_reg_1045),
    .spec_select504(spec_select504_reg_995),
    .row_ind_V_30_cast(empty_46_reg_1050),
    .spec_select508(spec_select508_reg_1000),
    .cmp_i_i73_i_not(cmp_i_i73_i_not_reg_964),
    .p_threshold_cast(p_threshold),
    .b0(b0_reg_893),
    .p_threshold(p_threshold),
    .xor_ln425_1(xor_ln425_reg_1055),
    .img_width(img_width),
    .cmp_i_i49_i(rev155_reg_1015),
    .cmp_i_i381_i(cmp_i_i381_i_reg_937),
    .p_0_0_01084242_out_i(p_0_0_010842_lcssa550_fu_172),
    .p_0_0_01084242_out_o(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_p_0_0_01084242_out_o),
    .p_0_0_01084242_out_o_ap_vld(grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_p_0_0_01084242_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln1027_3_fu_475_p2 == 1'd0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_start_reg <= 1'b1;
        end else if ((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_ready == 1'b1)) begin
            grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_start_reg <= 1'b0;
    end else begin
        if ((~((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_start_reg <= 1'b1;
        end else if ((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_ready == 1'b1)) begin
            grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_start_reg <= 1'b1;
        end else if ((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_ready == 1'b1)) begin
            grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_start_reg <= 1'b1;
        end else if ((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_ready == 1'b1)) begin
            grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        init_buf_fu_112 <= zext_ln541_fu_348_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln1027_fu_364_p2 == 1'd1))) begin
        init_buf_fu_112 <= add_ln506_fu_373_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln1027_fu_364_p2 == 1'd0))) begin
        row_V_fu_176 <= 13'd3;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln1027_3_fu_475_p2 == 1'd1))) begin
        row_V_fu_176 <= row_V_5_fu_506_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln1027_fu_364_p2 == 1'd0))) begin
        row_ind_V_19_fu_184 <= grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_10_out;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln1027_3_fu_475_p2 == 1'd1))) begin
        row_ind_V_19_fu_184 <= row_ind_V_20_fu_188;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln1027_fu_364_p2 == 1'd0))) begin
        row_ind_V_20_fu_188 <= grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_11_out;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln1027_3_fu_475_p2 == 1'd1))) begin
        row_ind_V_20_fu_188 <= row_ind_V_21_fu_192;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln1027_fu_364_p2 == 1'd0))) begin
        row_ind_V_21_fu_192 <= grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_12_out;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln1027_3_fu_475_p2 == 1'd1))) begin
        row_ind_V_21_fu_192 <= row_ind_V_22_fu_196;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln1027_fu_364_p2 == 1'd0))) begin
        row_ind_V_22_fu_196 <= grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_13_out;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln1027_3_fu_475_p2 == 1'd1))) begin
        row_ind_V_22_fu_196 <= row_ind_V_23_fu_200;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln1027_fu_364_p2 == 1'd0))) begin
        row_ind_V_23_fu_200 <= grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_14_out;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln1027_3_fu_475_p2 == 1'd1))) begin
        row_ind_V_23_fu_200 <= row_ind_V_24_fu_204;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln1027_fu_364_p2 == 1'd0))) begin
        row_ind_V_24_fu_204 <= grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_15_out;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        row_ind_V_24_fu_204 <= row_ind_V_fu_180;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln1027_fu_364_p2 == 1'd0))) begin
        row_ind_V_fu_180 <= grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_out;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        row_ind_V_fu_180 <= row_ind_V_25_reg_898;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_i_i66_reg_877 <= add_i_i66_fu_420_p2;
        b0_reg_893 <= b0_fu_440_p2;
        op2_assign_reg_882 <= op2_assign_fu_426_p2;
        sub350_i_reg_887 <= sub350_i_fu_431_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln1027_3_fu_475_p2 == 1'd1))) begin
        cmp_i_i329_i_reg_942 <= cmp_i_i329_i_fu_485_p2;
        cmp_i_i381_i_reg_937 <= cmp_i_i381_i_fu_480_p2;
        cmp_i_i73_i_not_reg_964 <= cmp_i_i73_i_not_fu_500_p2;
        sub_i_i297_i_reg_953 <= sub_i_i297_i_fu_490_p2;
        ult_reg_959 <= ult_fu_495_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln1027_fu_364_p2 == 1'd1))) begin
        empty_37_reg_811 <= empty_37_fu_369_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        empty_39_reg_1005 <= empty_39_fu_649_p1;
        spec_select484_reg_970 <= spec_select484_fu_559_p2;
        spec_select488_reg_975 <= spec_select488_fu_570_p2;
        spec_select492_reg_980 <= spec_select492_fu_591_p2;
        spec_select496_reg_985 <= spec_select496_fu_602_p2;
        spec_select500_reg_990 <= spec_select500_fu_623_p2;
        spec_select504_reg_995 <= spec_select504_fu_634_p2;
        spec_select508_reg_1000 <= spec_select508_fu_644_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        empty_40_reg_1020 <= empty_40_fu_663_p1;
        empty_41_reg_1025 <= empty_41_fu_668_p1;
        empty_42_reg_1030 <= empty_42_fu_672_p1;
        empty_43_reg_1035 <= empty_43_fu_676_p1;
        empty_44_reg_1040 <= empty_44_fu_680_p1;
        empty_45_reg_1045 <= empty_45_fu_684_p1;
        empty_46_reg_1050 <= empty_46_fu_688_p1;
        rev155_reg_1015 <= rev155_fu_657_p2;
        row_ind_V_load_reg_1010 <= row_ind_V_fu_180;
        xor_ln425_reg_1055 <= xor_ln425_fu_692_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_reg_770 <= empty_fu_323_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_p_0_0_01084242_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        p_0_0_010842_lcssa550_fu_172 <= grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_p_0_0_01084242_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        row_ind_V_25_reg_898 <= row_ind_V_19_fu_184;
        row_ind_V_26_reg_905 <= row_ind_V_20_fu_188;
        row_ind_V_27_reg_911 <= row_ind_V_21_fu_192;
        row_ind_V_28_reg_917 <= row_ind_V_22_fu_196;
        row_ind_V_29_reg_923 <= row_ind_V_23_fu_200;
        row_ind_V_30_reg_929 <= row_ind_V_24_fu_204;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        zext_ln506_reg_803[12 : 0] <= zext_ln506_fu_352_p1[12 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if (((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln1027_3_fu_475_p2 == 1'd0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_3_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_address1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_3_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_3_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_3_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_3_address1;
    end else begin
        buf_V_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_3_ce0 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_ce0;
    end else begin
        buf_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_3_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_ce1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_3_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_3_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_3_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_3_ce1;
    end else begin
        buf_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_3_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_d1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_3_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_3_d1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_3_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_3_d1;
    end else begin
        buf_V_3_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_3_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_3_we1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_3_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_3_we1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_3_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_3_we1;
    end else begin
        buf_V_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_4_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_address1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_4_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_4_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_4_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_4_address1;
    end else begin
        buf_V_4_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_4_ce0 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_ce0;
    end else begin
        buf_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_4_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_ce1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_4_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_4_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_4_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_4_ce1;
    end else begin
        buf_V_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_4_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_d1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_4_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_4_d1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_4_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_4_d1;
    end else begin
        buf_V_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_4_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_4_we1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_4_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_4_we1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_4_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_4_we1;
    end else begin
        buf_V_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_5_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_5_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_5_address1;
    end else begin
        buf_V_5_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_5_ce0 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_ce0;
    end else begin
        buf_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_5_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_5_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_5_ce1;
    end else begin
        buf_V_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_5_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_d1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_5_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_5_d1;
    end else begin
        buf_V_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_5_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_5_we1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_5_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_5_we1;
    end else begin
        buf_V_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_6_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_6_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_6_address1;
    end else begin
        buf_V_6_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_6_ce0 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_ce0;
    end else begin
        buf_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_6_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_6_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_6_ce1;
    end else begin
        buf_V_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_6_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_d1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_6_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_6_d1;
    end else begin
        buf_V_6_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_6_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_6_we1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_6_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_6_we1;
    end else begin
        buf_V_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_7_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_7_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_7_address1;
    end else begin
        buf_V_7_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_7_ce0 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_ce0;
    end else begin
        buf_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_7_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_7_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_7_ce1;
    end else begin
        buf_V_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_7_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_d1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_7_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_7_d1;
    end else begin
        buf_V_7_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_7_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_7_we1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_7_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_7_we1;
    end else begin
        buf_V_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_8_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_8_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_8_address1;
    end else begin
        buf_V_8_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_8_ce0 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_ce0;
    end else begin
        buf_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_8_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_8_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_8_ce1;
    end else begin
        buf_V_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_8_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_d1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_8_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_8_d1;
    end else begin
        buf_V_8_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_8_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_8_we1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_8_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_8_we1;
    end else begin
        buf_V_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_address1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_address1;
    end else begin
        buf_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_ce0 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_ce0;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_ce1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_ce1;
    end else begin
        buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_d1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_d1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_d1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_d1;
    end else begin
        buf_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_buf_V_we1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_buf_V_we1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_we1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_buf_V_we1;
    end else begin
        buf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        imgInput_data1_read = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_imgInput_data1_read;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        imgInput_data1_read = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_imgInput_data1_read;
    end else begin
        imgInput_data1_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln1027_3_fu_475_p2 == 1'd0))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_dst_data1_write = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_p_dst_data1_write;
    end else begin
        p_dst_data1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_height_c_blk_n = p_image_height_c_full_n;
    end else begin
        p_image_height_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_height_c_write = 1'b1;
    end else begin
        p_image_height_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_width_c_blk_n = p_image_width_c_full_n;
    end else begin
        p_image_width_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_width_c_write = 1'b1;
    end else begin
        p_image_width_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln1027_fu_364_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln1027_3_fu_475_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_i_i66_fu_420_p2 = (conv3_i_i_i61_fu_417_p1 + 17'd3);

assign add_ln506_fu_373_p2 = (init_buf_fu_112 + 64'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call32 = ((p_image_width_c_full_n == 1'b0) | (p_image_height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign b0_fu_440_p2 = (9'd0 - p_threshold_cast_fu_437_p1);

assign cmp_i_i253_i_1_fu_564_p2 = (($signed(sub_i273_i_fu_545_p2) < $signed(18'd1)) ? 1'b1 : 1'b0);

assign cmp_i_i253_i_3_fu_596_p2 = (($signed(sub_i273_i_fu_545_p2) < $signed(18'd3)) ? 1'b1 : 1'b0);

assign cmp_i_i253_i_5_fu_628_p2 = (($signed(sub_i273_i_fu_545_p2) < $signed(18'd5)) ? 1'b1 : 1'b0);

assign cmp_i_i253_i_6_fu_639_p2 = (($signed(sub_i_i297_i_reg_953) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign cmp_i_i329_i_fu_485_p2 = (($signed(sub350_i_reg_887) < $signed(zext_ln1027_3_fu_471_p1)) ? 1'b1 : 1'b0);

assign cmp_i_i381_i_fu_480_p2 = ((zext_ln1027_fu_467_p1 < img_height) ? 1'b1 : 1'b0);

assign cmp_i_i73_i_not_fu_500_p2 = ((row_V_fu_176 < 13'd6) ? 1'b1 : 1'b0);

assign conv3_i_i_i61_fu_417_p1 = img_height;

assign empty_37_fu_369_p1 = init_buf_fu_112[2:0];

assign empty_39_fu_649_p1 = sub_i273_i_fu_545_p2[2:0];

assign empty_40_fu_663_p1 = row_ind_V_fu_180[2:0];

assign empty_41_fu_668_p1 = row_ind_V_25_reg_898[2:0];

assign empty_42_fu_672_p1 = row_ind_V_26_reg_905[2:0];

assign empty_43_fu_676_p1 = row_ind_V_27_reg_911[2:0];

assign empty_44_fu_680_p1 = row_ind_V_28_reg_917[2:0];

assign empty_45_fu_684_p1 = row_ind_V_29_reg_923[2:0];

assign empty_46_fu_688_p1 = row_ind_V_24_fu_204[2:0];

assign empty_fu_323_p1 = img_width[13:0];

assign grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_start = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_ap_start_reg;

assign grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_start = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_ap_start_reg;

assign grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_start = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_ap_start_reg;

assign grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_510_2_fu_253_imgInput_data1_num_data_valid = imgInput_data1_num_data_valid;

assign grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_start = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_521_3_fu_268_ap_start_reg;

assign icmp154_fu_617_p2 = (($signed(tmp_3_fu_607_p4) < $signed(16'd1)) ? 1'b1 : 1'b0);

assign icmp_fu_585_p2 = (($signed(tmp_2_fu_575_p4) < $signed(17'd1)) ? 1'b1 : 1'b0);

assign icmp_ln1027_3_fu_475_p2 = ((zext_ln1027_3_fu_471_p1 < add_i_i66_reg_877) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_364_p2 = ((init_buf_fu_112 < zext_ln506_reg_803) ? 1'b1 : 1'b0);

assign op2_assign_fu_426_p2 = (empty_reg_770 + 14'd3);

assign p_dst_data1_din = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_Col_Loop_fu_276_p_dst_data1_din;

assign p_image_height_c_din = img_height;

assign p_image_width_c_din = img_width;

assign p_threshold_cast_fu_437_p1 = p_threshold;

assign rev155_fu_657_p2 = (ult_reg_959 ^ 1'd1);

assign row_V_5_fu_506_p2 = (row_V_fu_176 + 13'd1);

assign spec_select484_fu_559_p2 = (tmp_fu_551_p3 & cmp_i_i329_i_reg_942);

assign spec_select488_fu_570_p2 = (cmp_i_i329_i_reg_942 & cmp_i_i253_i_1_fu_564_p2);

assign spec_select492_fu_591_p2 = (icmp_fu_585_p2 & cmp_i_i329_i_reg_942);

assign spec_select496_fu_602_p2 = (cmp_i_i329_i_reg_942 & cmp_i_i253_i_3_fu_596_p2);

assign spec_select500_fu_623_p2 = (icmp154_fu_617_p2 & cmp_i_i329_i_reg_942);

assign spec_select504_fu_634_p2 = (cmp_i_i329_i_reg_942 & cmp_i_i253_i_5_fu_628_p2);

assign spec_select508_fu_644_p2 = (cmp_i_i329_i_reg_942 & cmp_i_i253_i_6_fu_639_p2);

assign start_out = real_start;

assign sub350_i_fu_431_p2 = ($signed(conv3_i_i_i61_fu_417_p1) + $signed(17'd131071));

assign sub_i273_i_fu_545_p2 = ($signed(18'd6) - $signed(sub_i_i297_i_cast_fu_542_p1));

assign sub_i_i297_i_cast_fu_542_p1 = sub_i_i297_i_reg_953;

assign sub_i_i297_i_fu_490_p2 = (zext_ln1027_3_fu_471_p1 - sub350_i_reg_887);

assign tmp_2_fu_575_p4 = {{sub_i273_i_fu_545_p2[17:1]}};

assign tmp_3_fu_607_p4 = {{sub_i273_i_fu_545_p2[17:2]}};

assign tmp_fu_551_p3 = sub_i273_i_fu_545_p2[32'd17];

assign ult_fu_495_p2 = ((zext_ln1027_fu_467_p1 < img_height) ? 1'b1 : 1'b0);

assign xor_ln425_fu_692_p2 = (cmp_i_i73_i_not_reg_964 ^ 1'd1);

assign zext_ln1027_3_fu_471_p1 = row_V_fu_176;

assign zext_ln1027_fu_467_p1 = row_V_fu_176;

assign zext_ln506_fu_352_p1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_15_out;

assign zext_ln541_fu_348_p1 = grp_xFfast7x7_0_128_128_0_1_1_131_7_49_3_Pipeline_VITIS_LOOP_495_1_fu_242_row_ind_V_12_out;

always @ (posedge ap_clk) begin
    zext_ln506_reg_803[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
end

endmodule //fast_corner_detect_xFfast7x7_0_128_128_0_1_1_131_7_49_3
